
import streamlit as st
#from streamlit_image_coordinates import streamlit_image_coordinates
import gettext

localizator = gettext.translation('messages', localedir='locales', languages=[st.session_state.itaolang])
localizator.install() 
_ = localizator.gettext 



en_itao = _('''
"iTao" is an abbreviation of the expression "I am Tao". In ancient times, human beings possessed a vague, instinctive perception of what was called the Tao. Ancient sages perceived Tao as All, as the goal and the path to that goal. Instead of direct perception, modern man employs concepts regarding the Tao that allow to make three assertions. These can be considered as the axioms of the spiritual science or the science of Tao. Just as the science of geometry is built upon Euclid’s axioms, so too can a science of Tao be constructed upon these assertions.

Since "Tao is All" it can only be defined in terms of itself. Therefore, Tao also signifies "I am the 'I Am'". As there cannot be two "All", the Tao is referred to as the "One without the Other". Tao must possess consciousness; otherwise, man - as a part of All - likewise lack consciousness. Names such as God, Brahman, Allah, and the Absolute are also designations for Tao. Tao cannot be defined, for All is infinite and encompasses all concepts inside itself. One can only assert that Tao is conscious and infinite. In other words, this means that the absolute, infinite God is self-conscious, and that whatever a human being is - or is not - capable of realizing exists inside the consciousness of God, who is All.

One must distinguish the concepts of infinity from the conscious Infinity itself, which is All and encompasses all concepts. For example, the concept of the infinity of natural numbers is based on the assumption that the number 1 can be added to any natural number N. Yet this is not a definition of Infinity, but merely a finite concept presupposing the existence of any number N - an assumption that is incorrect. Something finite cannot define the Infinite, which is All. 

Tao is the one, infinite, conscious source of everything that a human being is capable or incapable to perceive. Tao is also the one, absolute, infinite, conscious reality that is All. Therefore, the following assertion can be made.

Tao is self-conscious.

Since Tao exists and is self-conscious, it always exists and is self-conscious. There can be no state in which Tao is not self-conscious; otherwise, it would not be All. Only that which is All can possess infinite consciousness or be infinite; therefore, consciousness of Tao is infinite. A finite consciousness of Tao would imply the existence of something outside its consciousness. However since Tao is All, everything that can exist must also be inside consciousness of Tao.

Consciousness and existence are inseparable. Since the consciousness of Tao is infinite, there can be neither beginning nor end to the possibilities of manifestation inside the consciousness of Tao. To be manifested - or to be a being - always means to be inside the consciousness of Tao and to have finite consciousness. The finite consciousness is to be understood in the sense that it does not encompass All. Everything that is manifested will henceforth be referred to as the manifested world structure, or simply the world structure.

The concept of consciousness cannot be defined, because it is impossible to define the infinite consciousness of Tao, inside within whose consciousness everything, including all concepts, resides. Tao possesses absolute freedom of choice, for there is nothing that could make its choice unfree. Since Tao within itself can only be conscious of itself, it possesses the highest self-consciousness, or the highest "I-consciousness." As Tao is All, it possesses the supreme knowledge called as all-knowledge or omniscience.

Despite its omniscience, there is always something that Tao does not know. That is the free choice of a being in advance. If Tao is conscious of a being with free choice, it can never know in advance what free choice that being will make through Tao. If the choice were known beforehand, it would not be free. A being's free choice already implies that the choice remains unknown until it is determined. Tao is always conscious of all possibilities of free choice - for it is All, and is always self-conscious - yet the being's actual free choice becomes known to Tao only when the being itself determines it. Hereafter, a being possessing free choice will be referred to as a free being or a personality.

Not only must all knowledge be contained inside Tao, but everything that might be unknown to Tao - all unknowledge - must also be contained inside Tao itself. If there is something unknown to Tao, the Tao must always be aware that it does not know that something. Such unknowledge is the free choice of a human being as a free being, as a personality. Indeed, since all knowledge now belongs to Tao, it is always aware of all the possibilities of free choice that a personality might select. A free choice that is unknown to Tao cannot be known to any other being either. However, the moment a personality makes a choice through Tao, that choice immediately becomes known to Tao, because the personality - as well as all possibilities of free choice - exists inside the consciousness of Tao.

Every being always has a beginning and an end and always exists inside the consciousness of Tao. The Tao itself is infinite and cannot be a finite being. Therefore, Tao can never know in advance what choice a personality will make. Since Tao is conscious of everything the personality is aware of, it is also conscious of unknowledge of personality. If there were no personalities, then through beings without free choice, Tao could only be conscious of its own infinite knowledge, because in a being without freedom, everything is already known to Tao.

Thus, unknowledge always exists inside Tao and transforms into knowledge only when personality makes a free choice. It would be a mistake to conclude that, simply because something unknown to  Tao can become known through personality, the consciousness of Tao itself evolves. Concepts of development and change apply only to the finite consciousness of a being. The Tao’s infinite consciousness of all the possibilities and consequences of a personality’s free choice does not change when a choice is made, for they are always inside the consciousness of Tao. For this reason alone, it would be incorrect to claim that consciousness of Tao can evolve or change. Tao knows all things through infinite consciousness, yet it does not know all things through the finite consciousness of personality. Were the Tao not to manifest itself within the personality, unknowledge could never become knowledge, and there would be no manifestation of the world structure in which personality could make free choice.

The concept of freedom of choice is inseparable from the concept of will. To manifest will means to make a choice through Tao. Therefore, freedom of choice and freedom of will signify the same thing. Consciousness always precedes the choice made, because before a free choice can be made at all, personality must be aware of at least two possible options. If only one possibility existed for the consciousness of personality, such a choice would not be free.

Consciousness and Tao are inseparable; therefore, the consciousness of a personality is always imbued with Tao, which possesses absolute free will. Consequently, the consciousness of a personality is always imbued with will, meaning that if a choice exists, personality is capable of making a free choice through Tao. Only beings without free choice can carry out any free choice made by personality. If only personalities existed, then any choice made by one personality would have to be executed by other personalities. This implies that those other personalities would lack free choice. Therefore, any manifested world structure must always consist of both personalities and beings without free choice.

Animals, for example, are beings without free choice. Suppose an animal is presented with two pieces of food - one of them poisoned - and consciousness (commonly termed "instinct") capable of identifying the poisoned piece. The animal will never eat the poisoned piece; instead, it will choose the other. An animal's actions are predetermined by instinct. Instinct is the consciousness of an entire species - or of animals of the same kind - that invariably dictates the actions of the individual of species. Instinct operates according to a predictable pattern. Human behavior, however, cannot be predicted in this way because humans possess free choice. Even if a personality knows which piece of food is poisoned, the choice is not predetermined yet.

In spiritual science, beings whose consciousness encompasses the consciousness of all animals of a single species are called group souls. An animal's instinct is the consciousness of that animal's group soul. Animal group souls do not possess freedom of choice; therefore, individual animals cannot possess freedom of choice either. It follows that a human being cannot have originated from an animal. A personality can only originate from those that possesses freedom of choice - that is, from Tao. The personality is made in the image and likeness of the absolute God, because God's freedom of choice is manifested in the personality's freedom of choice.

Only personality - and not the Tao, inside whose consciousness all possibilities of free choice reside - can ever be held responsible for the consequences of free choice. Free choice is always a cause that invariably and precisely leads to corresponding consequences. Therefore, in exercising free choice, a personality may suffer from that choice, rather than for it. To suffer from free choice means to suffer as a result of free choice acting as the cause. To suffer for free choice would imply the existence of punishment for making that choice. No such punishment can exist, for then the choice would not be free; instead, it would be predetermined by the prospect of punishment through suffering. This helps explain why the absolute God allows personalities to commit crimes, steal, lie, and inflict suffering upon one another: because otherwise, personalities would be deprived of free choice.

The Sanskrit word karma means "deed, action". Since any action would be predetermined in the absence of free will, karma always signifies a free action - that is, an action resulting from free choice. The relationship between the cause and effect of an personality's free choice is also known as the law of destiny or the law of karma. In this sense, karma should always be understood as the consequences of actions stemming from free choice. Without free choice, there can be no karma.

The law of cause and effect inexorably leads the personality to the next free choice. The personality's successive free choices determine its destiny - its karma. It is impossible to predict a future free choice; one can only predict the consequences of such a choice. Therefore, religious sources that foretell the future can only indicate the consequences of free choices that personalities have already made.

When a personality suffers, it is said that it has bad karma. Whether a personality has bad or good karma depends solely on its free choice. Since animals lack free choice, they do not generate karma and should not suffer, as their actions are always dictated by instinct - which operates without free will. Instinct, for instance, always protects an animal from suffering; thus, an animal can never voluntarily choose to suffer. To understand what might cause animal suffering, let us consider the following statement.

Man is the only being with freedom of choice in the manifested world structure.

The second assertion provides an unequivocal characterization of the human being as a personality, making it possible to answer the question: "What is a human being?" A human being is a being possessed of free choice. If even a single personality exists, there must be a world structure in which that personality can become conscious of and make a free choice. Therefore, the "manifested world structure" will henceforth be understood as everything that a human being can possibly perceive through free choice. This also implies that all possibilities for free choice must already exist within the world structure, just as the world structure itself must exist within the consciousness of Tao. The world structure must also possess consciousness, because everything of what Tao is conscious of, possesses consciousness.

If there were no personalities within the manifested world structure, then such a world structure - lacking free choice itself - would contain no free life. Free life is the transformation of consciousness through free choice. The transformation of a personality's consciousness through free choice also implies that something previously unknown to Tao becomes known. A manifestation of the world structure without personalities would immediately come to an end, because in such a world structure, everything would already be known to Tao in advance. Therefore, a world structure without personalities cannot manifest. Likewise, personalities cannot manifest without a world structure that holds within its consciousness all the possibilities for their free choice.

The possession of free choice renders all personalities potentially equal regarding the free development of the ’I’-consciousness. This implies that every personality, without exception, must always have the potential to realize themselves as the absolute ’I’ - as Tao. Were this not the case, Tao - in order to avoid violating an personality's free choice - would have to act solely through beings without free choice, thereby forever depriving itself of free choice. Since this is impossible, there can be only one type of beings possessing the free choice who can develop consciousness and realize itself as Tao. The existence of two distinct types of personalities would imply inequality in the development of the ’I’-consciousness: one type would have the capacity to realize itself as the Tao, while the other would not. Human free choice allows to assert that man must be the only one free being in the manifested world structure.

The manifestation of a human being as a being with free choice entails the manifestation of all other beings without free choice, including animals. The free choice influences not only one’s own consciousness but also the consciousness of other beings. Beings without free choice are always dependent on beings with free choice. Therefore, the cause of animal suffering can only be human free choice. This renders the human being responsible for the suffering not only of animals but of any being in the manifested world structure. From this, one can understand that the absolute God never punishes anyone; rather, it is solely the free choice of the personality that can be the cause of suffering.


Everything that can exist must possess consciousness, because everything resides within the consciousness of Tao, which is alway self-conscious. A man who acknowledges his own consciousness yet denies consciousness in the multiplicity of the external environment would be like someone who acknowledges the air in his lungs while denying the existence of air outside his physical body. The concept of a "being" is identical to the concept of "consciousness," in the sense that there are no beings without consciousness and no consciousness without beings to manifest it. Therefore, what can be chosen, developed, or altered in the manifested world structure is consciousness itself, for everything manifested appears as beings possessing varying levels of consciousness. Since everything possesses consciousness, and the manifested world structure consists of both beings with free choice and beings without it, all possibilities of the free choice can only be manifested through beings without free choice.

The manifestation or emanation of all beings occurs through the Tao’s realization within itself of beings with free choice. The concept of a "being" cannot be applied to the Tao, because it implies the finitude or limitation of consciousness. The consciousness of Tao is infinite; therefore, Tao is not a being, but every being always exists in the consciousness of Tao.

The word "self-consciousness" implies a duality of consciousness - the capacity to become conscious of oneself within oneself. That what Tao is conscious of in itself possesses consciousness itself and becomes a relative consciousness. Duality also signifies the existence of two opposites. A consequence of this duality of consciousness is the existence, in the manifested world structure, of both beings with free choice and beings without it.

If a human possesses free choice, then there must exist beings without free choice. The existence of beings with varying levels of consciousness implies the existence of hierarchies of beings - or hierarchies of consciousness. Hierarchies of beings without free choice cannot lie or deny what exists, for doing so would imply the possession of free choice. They can only be what they are conscious of. In this sense, the consciousness of beings without free choice is always true. A human comes to know the truth when they perceive what is perceived by hierarchies of consciousness without free choice. Since the consciousness of any being is finite, these hierarchies of consciousness can reflect only relative truth. A human can grasp the truth only gradually, by attaining various levels of the hierarchies of consciousness. To know absolute truth would mean knowing what Tao is conscious of, or attaining the realization of oneself as Tao.

The existence of hierarchies of consciousness makes it possible to answer the question: "Which came first - a chicken or an egg?" Neither. The egg and the chicken are distinct manifestations of beings of the hierarchies of consciousness. Everything that is manifest is manifest through hierarchies of consciousness. Laws of nature are likewise relationships between hierarchies of consciousness without free choice. Natural science is possible only because there exist hierarchies of beings without free choice, the relationships between which can be predicted. Natural science investigates the relationships accessible to what is known as human waking - or daytimeconsciousness. Accessible to human waking consciousness are those relationships between hierarchies of consciousness known as the solid, liquid, gaseous, and fiery states. In spiritual science, these four states of relationship between hierarchies of consciousness are termed Earth, Water, Air, and Fire.

If a man has developed spiritual or supersensible organs of perception, then the consciousness of dreaming sleep, dreamless sleep, and deep dreamless sleep can be integrated into his waking consciousness. Waking consciousness that incorporates the consciousness of dreaming sleep is termed imaginative consciousness. Waking consciousness that encompasses the consciousness of dreamless sleep is termed inspirative consciousness. Waking consciousness that includes the consciousness of deep dreamless sleep is termed intuitive consciousness. Imaginative consciousness perceives the consciousness of the hierarchies in animals. Inspirative consciousness perceives the consciousness of the hierarchies in plants. Intuitive consciousness perceives the consciousness of the hierarchies in minerals. For supersensible perception, the consciousness of all things is an immediate fact.

Everything that is manifested as hierarchies of consciousness can only have finite consciousness, because only Tao has infinite consciousness. Since the world structure is manifested, it must have consciousness, and its consciousness must be finite. This leads to the third statement.

Any manifested world structure is finite.

The finite nature of the world structure implies that the world structure has a beginning and an end. The manifestation of the world structure begins with Tao realizing within itself the personalities as beings with free choice. The world structure ends when personalities realize themselves as Tao. Since Tao is always self-conscious and its consciousness is infinite, countless manifested world structures have already existed. In the infinity of Tao’s consciousness, there can be no first or last world structure. Therefore, there always exist countless possibilities for the manifestation of world structures in which personalities have not yet realized themselves as Tao through free choice. Consequently, the past, present, and future are inextricably linked to the individual's free choice. Without free choice of personality, there would be neither past, present, nor future, for everything would be known to Tao in advance.

The third assertion can also be stated as follows:

The number of personalities in any manifested world structure is finite.

Let us assume that the manifested world structure is finite, yet the number of personalities in it were infinite. In that case, there would always be personalities with distinct consciousnesses who had not yet made the possible free choice - and, consequently, had not realized themselves as Tao. Such a world structure would never come to an end, which contradicts the premise that the world structure is finite. Therefore, the number of personalities - as beings possessing free choice - must always be finite in any manifested world structure.

Conversely, if we assume that the number of personalities in the manifested world structure is always finite, then the world structure itself must also be finite. An infinite world structure would consist of countless possibilities for free choice of personalities. The free choice of personalities in an infinite universe would never come to an end, and personalities would never be able to realize themselves as  Tao. It follows, then, that Tao would forever deprive itself of free choice by manifesting that freedom through personalities. Thus, the manifested world structure is always realized by Tao as an being whose consciousness is composed of the finite set of all possibilities that personalities can choose in order to realize themselves as Tao. Since the world structure and personalities cannot manifest without one another, both versions of the third assertion are equivalent.

The word "monad," translated from Greek, signifies "unit" or "the one" and implies indivisibility - in the sense that nothing can be separated from the unified whole without destroying that unity. The word "individuality," translated from Latin, signifies "indivisibility" and, in this sense, denotes the same concept as the monad. The concepts of individuality and monad should be understood namely as a whole from which nothing can be separated without destroying its unity.


Man realizes himself as a separate being, as the "I." This means he possess self-consciousness - the "I-am" consciousness or the "I-consciousness." The highest "I-consciousness" has Tao, which is indivisible; because nothing can be separated from it, and it constitutes an absolute individuality. Therefore, a man's true "I" - or true self - can only be that absolute individuality which is Tao.


The highest "I" of man is manifested in the world structure as his individuality. The individuality of man  can also be defined as the highest "I-consciousness." a man can have in the manifested world structure. In order all personalities to be equally free, their individualities must be potentially equal. This is possible if each individuality encompasses all the possibilities of free choice available to the personality. The full range of possibilities for a personality's free choice remains constant in the manifested world structure; in this sense, individuality, too, remains unchanged in the manifested cosmos.

The extent to which a man is conscious of himself as individuality defines him as personality. A human being is together individuality, personality, and the relationships between hierarchies of consciousness manifested through free choice. There is an ancient knowledge that a man consists of spirit, soul, and body. Individuality corresponds to the spirit. Personality corresponds to the soul. The body corresponds to karma - or the relationships between hierarchies of consciousness manifested through free choice.

Personality is defined by consciousness of man and, consequently, changes evolving through the free choice. A man's individuality is his highest manifested "I"; it is indivisible and constitutes the principle of personality. Personality cannot be separated from individuality, just as individuality cannot be separated from mankind. The consciousness that Tao realizes in itself as the consciousness of all personalities must be understood as the consciousness of mankind. Mankind is not merely the aggregate of all personalities; rather, mankind is a being whose consciousness encompasses the consciousness of every personality. Before a personality can be manifested, mankind must be manifested as a being possessing the free choice of all personalities. When the consciousness of each personality attains the awareness of its own individuality, the end of the world structure arrives, and all personalities attain the realization of themselves as an absolute, unified individuality - as the absolute "I", as Tao. This marks the return of individuality - or the human monad - to its source: the absolute Deity.

The concepts of consciousness and free will are fundamental to understanding the possibility of the beginning and end of the manifested world structure. The world structure begins with the Tao’s free choice to manifest in itself personalities as beings with free choice. The world structure exists as long as there remains even a single personality that has not yet attained the realization of itself as an individuality in the manifested world structure. The world structure comes to an end through the free choice of every personality to realize itself as the absolute individuality that is Tao. This is possible only when every personality has already attained the highest consciousness of itself as an individuality in the manifested world structure. Only then can one personality, as an individuality, realize all other personalities as individualities. If even a single personality lacks this highest consciousness of self as an individuality, it implies that no other personality possesses such highest consciousness either, given the potential equality of individualities. Therefore, a single personality’s realization of itself as Tao can occur only in conjunction with all other personalities. This means that no man can merge with  Tao - that is, realize itself as Tao - until another man is also able to merge with Tao.

The number of personalities must be finite in any manifested world structure. Yet, this number must also differ across different world structures. If the number of personalities in a preceding and a succeeding world structure were identical, they would constitute the very same personalities, given the potential equality of individualities. Consequently, both world structures would be exactly the same. Any choice made would not be free, but rather predetermined by the previous world structure; therefore, such a succeeding world structure cannot come into manifestation.

As distinct beings, personalities must possess distinct consciousness. Personalities may share the same level of consciousness, yet their consciousness remain distinct. This implies that, in the manifested world structure, there always exist personalities possessing higher or lower levels of consciousness. Consequently, there must also exist a personality in our manifested world structure that has the highest consciousness of self as an individuality. This is the personality referred to in the New Testament as Jesus Christ. The name "Jesus" corresponds to the consciousness of personality, while "Christ" corresponds to the consciousness of individuality - representing the highest self-consciousness in our manifested world structure.

The existence of personality’s freedom of choice allows us to pose a question to which there can be no answer in the manifested world structure:

What is the number of personalities in the manifested world structure?

The number of personalities in the manifested world structure is always finite. This number is known only to the infinite consciousness of Tao, which realizes in itself every personality as a being with free choice. To know the total number of personalities without violating the free choice, one must has a consciousness that encompasses all individualities. Such a consciousness of all individualities can be attained only through all personalities together. If all personalities were already conscious of themselves as individualities, then all possible choices and their consequences would be known to them in advance, and their choices would not be free. Consequently, a personality's freedom of choice implies that personality cannot know the finite number of all personalities in the manifested world structure. The answer will be revealed to all personalities only when each one has attained the highest consciousness of itself as an individuality within the manifested world structure. Only then can each personality, as an individuality, realize itself as the Tao and perceive all other personalities as individualities - thereby coming to know the number of personalities in the manifested world structure.

The finite number of personalities is a numerical characteristic of the world structure. It allows us to define the center of the manifested world structure. Since everything possesses consciousness, the center of the manifested world structure is that level of consciousness at which it is possible to know the finite number of personalities within the manifested world structure. At this level of consciousness, each personality realizes itself as an individuality, and all personalities together can realize themselves as an absolute individuality. This number lies at the foundation of all relationships between hierarchies of consciousness, regardless of whether or not they can be expressed in numerical terms. Without a finite number of personalities in the manifested world structure, there can be no manifestation of the world structure. Without a manifested world structure, there can be no science. Therefore, knowledge of the existence of a finite number of personalities in the manifested world structure lies at the base of the science of the Tao.
  
'''
)

de_itao = _('''

'''
)
 

ru_itao = _('''
                                                                                                          
                                                                      
iTao является сокращением выражения «Я есть Тао (I am Tao)». Человеческое существо в древности имело смутное инстинктивное восприятие того, что называли Тао. Тао воспринималось древними мудрецами как Всё, как цель и как путь к цели. Вместо непосредственного восприятия современный человек использует понятия о Тао, которые позволяют сделать три утверждения. Их можно рассматривать как аксиомы духовной науки или науки о Тао. Как на основе аксиом Евклида строится наука геометрии, так же на основе этих утверждений можно строить науку о Тао.  

Так как «Тао есть Всё», то оно может определяться только через само себя. Поэтому Тао также означает «Я есть Я-есть». Так как двух Всё быть не может, то Тао называют «Одно без Второго».  Тао должно обладать сознанием, иначе человек, как часть Всего, также не имел бы сознания. Такие названия, как Бог, Брахман, Аллах, Абсолют также являются обозначениями Тао.  Тао невозможно определить, так как Всё есть бесконечно и содержит в себе любые понятия. Возможно лишь утверждать, что Тао является сознательным и бесконечным. Другими словами это означает, что бесконечный Бог осознаёт себя и то, что человек способен или не способен осознать находится в сознании бесконечного Бога, который есть Всё.
 
Следует различать понятия о бесконечности от самой сознательной Бесконечности, которая есть Всё и содержит в себе любые понятия. Например, понятие о бесконечности натуральных чисел обосновывается тем, что к любому числу N можно прибавить число 1. Но это не есть определение Бесконечности, а лишь конечное понятие, предполагающее существование любого числа N, что является неверным. Нечто конечное не может определять Бесконечное, которое есть Всё.

Тао есть единый бесконечный сознательный источник всего, что человек способен или не способен осознать. Тао также есть единая бесконечная сознательная реальность, которая есть Всё. Поэтому возможно сделать следующее утверждение.

Тао осознаёт себя.

Так как Тао всегда существует и осознаёт себя, то оно существует и осознаёт себя всегда. Не может быть такого состояния, когда Тао себя не осознаёт, иначе оно не было бы Всё. Иметь бесконечное сознание, или быть бесконечным, может только то, что есть Всё, поэтому сознание Тао бесконечно. Конечность сознания Тао означала бы, что существует нечто вне его сознания. Но так как Тао есть Всё, то всё, что может существовать, также должно находиться в сознании Тао.

Сознание и существование неотделимы друг от друга. Так как сознание Тао бесконечно, то не может быть ни начала, ни конца возможностям проявлений в сознании Тао. Быть проявленным, или быть существом, всегда означает быть в сознании Тао и иметь конечное сознание. Конечное сознание следует понимать в том смысле, что оно не включает в себя Всё. Всё проявленное будет называться в дальнейшем проявленное мироздание, или просто мироздание.

Понятие сознание невозможно определить, потому что невозможно определить бесконечное сознание Тао, в сознании которого находится всё, включая любые понятия. Тао обладает абсолютной свободой выбора, потому что не существует ничего, что могло бы сделать его выбор не свободным. Так как в самом себе Тао может осознавать только себя, то оно обладает наивысшим сознанием себя или наивысшим Я-сознанием. Так как Тао есть Всё, то оно обладает наивысшим знанием, которое называют всезнанием. 

Не смотря на всезнание, всегда существует нечто, что Тао не знает. Это есть незнание Тао заранее свободного выбора существа. Если Тао осознаёт в себе существо со свободой выбора, то Тао никогда заранее не может быть известно, какой свободный выбор будет сделан таким существом через Тао. Если выбор был бы заранее известным, то он не был бы свободным. Свободный выбор существа уже подразумевает, что выбор не известен, пока он еще не определён. Тао всегда осознаёт все возможности свободного выбора, ибо оно есть Всё, и осознаёт себя всегда. Сам же свободный выбор существа становится известным Тао лишь тогда, когда он определён самим существом. Существо со свободой выбора будет называться в дальнейшем свободное существо или личность.

Не только всё знание должно заключаться в Тао, но также всё, что может быть неизвестно Тао, всё незнание, также должно заключаться в самом Тао. Если существует нечто неизвестное для Тао, то Тао всегда должно осознавать, что оно нечто не знает. Такое незнание есть свободный выбор человека как свободного существа, как личности. Действительно, всё знание теперь принадлежит Тао, поэтому ему всегда известны все возможности свободного выбора, которые могла бы выбрать личность. Свободный выбор, который неизвестен Тао, не может быть известен и никакому существу. Однако, как только личность делает выбор через Тао, то этот выбор сразу же известен Тао, потому что сама личность находится в сознании Тао, как и все возможности свободного выбора.

Любое существо всегда имеет начало и конец, и всегда находится в сознании Тао. Само Тао всегда бесконечно и не может быть конечным существом. Поэтому Тао никогда заранее не может знать, какой выбор сделает личность. Так как Тао осознаёт всё, что осознаёт личность, то оно осознаёт также и незнание личности. Если бы личностей не было, то через существ без свободы выбора Тао могло бы осознавать только своё бесконечное знание, потому что в несвободном существе Тао всё известно.

Таким образом, незнание всегда находится в Тао и становится знанием только тогда, когда личность делает свободный выбор. Было бы ошибкой сделать вывод, что если нечто неизвестное  Тао может стать известным через личность, то сознание Тао развивается. Понятия развития и изменения применимы только к конечному сознанию существа. Бесконечное осознание Тао всех возможностей и последствий свободного выбора личности не меняется, когда делается свободный выбор, потому что они всегда осознаются Тао. Уже поэтому было бы некорректно утверждать, что сознание Тао может развиваться и меняться. Тао знает всё через бесконечное сознание, но не знает всё через конечное сознание личности. Если бы Тао не проявляло себя в личности, то незнание никогда не могло бы стать знанием, и не было бы никакого проявления мироздания, в котором личность могла бы сделать свободный выбор.

Понятие свобода выбора неотделимо от понятия воля. Проявить волю - означает сделать выбор через Тао. Поэтому свобода выбора и свобода воли означают одно и то же. Сознание всегда первично по отношению к сделанному выбору, потому что прежде чем свободный выбор вообще может быть сделан, личность должна осознать по меньшей мере две возможности выбора. Если для сознания личности существовала бы только одна возможность, то такой выбор не был бы свободным.

Сознание и Тао неразделимы, поэтому сознание личности всегда проникнуто Тао, которое обладает абсолютной свободой воли. Следовательно, сознание личности всегда проникнуто волей, что означает, что если выбор существует, то личность способна сделать свободный выбор через Тао. Осуществить любой свободный выбор личности могут только существа без свободы выбора. Если бы существовали только личности, то любой выбор одной личности должен был бы осуществляться другими личностями. Это означает, что другие личности свободы выбора не имели бы. Поэтому любое проявленное мироздание всегда должно состоять из личностей и из существ, которые свободы выбора не имеют.


Животные, например, есть существа без свободы выбора. Предположим, перед животным находятся два кусочка пищи, один из которых отравлен, и сознание, которое обычно называют инстинктом, способно распознать, какой кусок отравлен. Тогда животное никогда не будет есть отравленный кусок, а предпочтёт взять другой. Действия животного предопределены инстинктом. Инстинкт - это сознание целого вида, или животных одного рода, которое всегда предопределяет действия отдельной особи вида. Инстинкт действует по схеме, которую можно предсказать. Схему действия человека предсказать невозможно, потому что он обладает свободой выбора. Если человеку известно, какой кусок пищи отравлен, то его выбор ещё не предопределён заранее.

В духовной науке существа, сознание которых охватывает сознание всех животных одного вида, называют групповыми душами. Инстинкт животного есть сознание групповой души животного. Групповые души животных свободы выбора не имеют, поэтому отдельные животные также не могут иметь свободу выбора. Значит, человек не может происходить от животного. Личность может происходить только от того, кто имеет свободу выбора, то есть от Тао. Личность является образом и подобием абсолютного Бога, потому что его свобода выбора проявлена в свободе выбора личности.

За последствия свободного выбора всегда может быть ответственна только личность, но не Тао, в сознании которого есть все возможности свободного выбора. Свободный выбор всегда является причиной, которая неизменно и точно приведёт к соответствующим последствиям. Поэтому человек, определяя свой свободный выбор, может страдать не за свой выбор, а от своего выбора. Страдать от свободного выбора - означает страдать вследствие свободного выбора как причины. Страдание за свободный выбор означало бы существование наказания за свободный выбор. Никакого наказания за свободный выбор существовать не может, потому что тогда выбор не был бы свободным, а предопределялся бы заранее наказанием через страдание. Это может сделать понятным то, почему абсолютный Бог позволяет личностям совершать преступления, воровать, лгать и причинять страдания друг другу. Потому что иначе личности были бы лишены свободы выбора.

Санскритское слово карма означает «действие». Так как без свободы выбора любое действие было бы заранее предопределённым, то карма всегда означает свободное действие, то есть действие через свободный выбор. Соотношение причины и следствия свободного выбора личности называют также законом судьбы или законом кармы. В этом смысле под кармой следует всегда понимать последствия действий через свободный выбор. Без свободы выбора не может быть и кармы.

Закон причины и следствия неумолимо приводит личность к следующему свободному выбору. Следующий один за другим свободный выбор личности определяет её судьбу, её карму. Предсказать будущий свободный выбор невозможно, возможно лишь предсказать последствия свободного выбора. Поэтому во всех религиозных источниках, в которых предсказывается будущее, могут быть указаны лишь последствия свободного выбора, который уже был сделан личностями.

Когда человек страдает, то говорят о его плохой карме. Имеет человек плохую или хорошую карму - это зависит только от его свободного выбора. Так как животные свободы выбора не имеют, то они не создают карму и не должны были бы страдать, ибо их выбор всегда определяется инстинктом, не обладающим свободой выбора. Инстинкт, например, всегда предохраняет животное от страдания, поэтому животное никогда не может выбрать страдание самостоятельно. Чтобы понять, что может быть причиной страдания животных, рассмотрим следующее утверждение.

Человек - единственное существо со свободой выбора в проявленном мироздании.

Второе утверждение даёт однозначную характеристику человека как личности, позволяя ответить на вопрос: «Что такое человек?» Человек - это существо, имеющее свободу выбора. Если существует хоть одна личность, то должно быть мироздание, в котором личность может осознать и сделать свободный выбор. Поэтому под проявленным мирозданием будет пониматься в дальнейшем всё то, что вообще возможно осознать человеку через свободу выбора. Это также означает, что все возможности свободного выбора должны уже быть в мироздании, так же, как и само мироздание должно быть в сознании Тао. Мироздание должно также обладать сознанием, потому что всё, что осознаётся Тао, имеет сознание.

Если в проявленном мироздании не было бы личностей, то такое мироздание, если оно само не обладает свободой выбора, не содержало бы в себе никакой свободной жизни. Свободная жизнь есть изменение сознания через свободный выбор. Изменение сознания личности через свободный выбор также означает, что нечто, ранее неизвестное Тао, становится известным. Проявление мироздания без личностей сразу бы заканчивалось, потому что в таком мироздании Тао всё уже заранее известно. Поэтому мироздание без личностей проявиться не может. Также и личности не могут проявиться без мироздания, содержащего в своём сознании все возможности свободного выбора личностей.

Наличие свободы выбора у личности делает все личности потенциально равными в отношении свободного развития Я-сознания. Это означает, что все личности без исключения должны всегда иметь потенциальную возможность осознать себя как абсолютное Я, как Тао. Если бы это было не так, то Тао, чтобы не нарушить свободный выбор личности, всегда должен был бы исполнять его через существа без свободы выбора, и навсегда лишил бы сам себя свободы выбора. Так как это - невозможно, то должен быть только один-единственный тип существ со свободой выбора развития сознания, которые могут осознать себя как Тао. Существование двух различных типов личностей означало бы неравенство развития Я-сознания. Один тип личностей имел бы возможность осознать себя как Тао, а другой - нет. Свобода выбора человека делает возможным утверждать, что человек должен быть единственным свободным существом в проявленном мироздании.

Проявление человека как существа со свободой выбора влечёт за собой проявление всех остальных существ, не обладающих свободой выбора, в том числе и животных. Свободный выбор человека влияет не только на его собственное сознание, но и на сознание других существ. Существа, не обладающие свободой выбора, всегда зависят от существ со свободой выбора. Поэтому причиной страдания животных может быть только свободный выбор человека. Это делает человека ответственным за страдания не только животных, но и вообще за страдания любого существа в проявленном мироздании. Отсюда можно понять, что абсолютный Бог никого никогда не наказывает, но только свободный выбор личности может быть причиной страдания.

Всё, что может существовать, должно обладать сознанием, потому что всё находится в сознании Тао, которое осознаёт себя всегда. Человек, признающий наличие сознания у себя и отрицающий сознание у множественности внешнего окружения, стал бы подобен человеку, который признавал бы наличие воздуха в своих лёгких и отрицал бы наличие воздуха вне своего физического тела. Понятие существо тождественно понятию сознание в том смысле, что нет существ без сознания и нет сознания без существ, которые проявляют это сознание. Поэтому то, что в проявленном мироздании может быть избрано, развито или изменено, это есть сознание, потому что всё, что проявлено, проявлено как существа с различными уровнями сознания. Так как всё имеет сознание, и проявленное мироздание всегда состоит из личностей и существ без свободы выбора, то все возможности выбора личности могут быть проявлены только через существ без свободы выбора.

Проявление или эманация всех существ происходит через осознание абсолютным Духом в себе существ, обладающих свободой выбора. Понятие существо не может быть применено к Тао, потому что оно предполагает конечность или ограниченность сознания. Сознание Тао бесконечно, поэтому Тао не есть существо, но любое существо всегда находится в сознании Тао.

Слово самосознание подразумевает двойственность сознания - возможность осознания себя в себе. То, что осознаёт в себе Тао, само обладает сознанием и становится относительным сознанием. Двойственность означает также существование двух противоположностей. Следствием двойственности сознания является существование в проявленном мироздании как существ со свободой выбора, так и существ, которые свободы выбора не имеют.

Если человек имеет свободу выбора, то должны существовать существа, которые свободы выбора не имеют. Наличие существ с различными уровнями сознания означает, что существуют иерархии существ, или иерархии сознания. Иерархии существ без свободы выбора не могут лгать, или отрицать то, что существует, потому что это означало бы наличие у них свободы выбора. Они могут быть только тем, что они осознают. В этом смысле сознание существ без свободы выбора всегда истинно. Человек познаёт истину, когда он познаёт то, что осознают иерархии сознания без свободы выбора. Так как сознание любого существа конечно, то иерархии сознания могут отражать только относительную истину. Познавать истину человек может только постепенно, достигая различных уровней иерархий сознания. Познать абсолютную истину означало бы познать то, что осознаёт Тао, или достичь осознания себя как Тао.

Наличие иерархий сознания позволяет дать ответ на следующий вопрос: «Что было раньше - курица или яйцо?». Ни то и ни другое. Яйцо и курица являются различными проявлениями существ иерархий сознания. Всё, что проявлено, проявлено через иерархии сознания. Законы природы также есть соотношения между иерархиями сознания без свободы выбора. Естественная наука вообще возможна лишь потому, что существуют иерархии существ без свободы выбора, соотношения между которыми можно предсказать. Естественная наука исследует соотношения, доступные так называемому бодрственному, или дневному, сознанию человека. Бодрственному сознанию человека доступны соотношения между иерархиями сознания, называемые твёрдое, жидкое, газообразное и огненное состояния. В духовной науке эти четыре состояния отношений между иерархиями сознания называют Земля, Вода, Воздух и Огонь.

Если у человека развиты духовные, или сверхчувственные органы восприятия, то в его дневное сознание могут быть включены сознание сна со сновидениями, сознание сна без сновидений и сознание глубокого сна без сновидений. Бодрственное сознание, которое включает в себя сознание сна со сновидениями, называется имагинативным сознанием. Инспиративным сознанием будет называться бодрственное сознание, которое охватывает сознание сна без сновидений. Бодрственное сознание, которое включает в себя сознание глубокого сна без сновидений, называется интуитивным сознанием. Имагинативное сознание воспринимает сознание иерархий в животных. Инспиративное сознание воспринимает сознание иерархий в растениях. Интуитивное сознание воспринимает сознание иерархий в минералах. Для сверхчувственного восприятия сознательность всего является непосредственным фактом.

Всё, что проявлено как иерархии сознания, может иметь только конечное сознание, потому что бесконечное сознание имеет только Тао. Так как мироздание проявле- но, то оно должно иметь сознание, и его сознание должно быть конечным. Это приводит к третьему утверждению.

Любое проявленное мироздание конечно.

Конечность мироздания подразумевает, что существует начало и конец мироздания. Проявление мироздания начинается с осознания Тао в себе личностей как существ со свободой выбора. Мироздание заканчивается через осознание личностями себя как Тао. Так как Тао осознаёт себя всегда и его сознание бесконечно, то уже существовало бесчисленное множество проявленных мирозданий. В бесконечности сознания  Тао не может быть первого или последнего мироздания. Поэтому всегда существуют бесчисленные возможности проявления мирозданий, в которых личности ещё не осознали себя через свободный выбор как Тао. Следовательно, прошлое, настоящее и будущее всегда связаны со свободой выбора личности. Без свободного выбора личности не было бы ни прошлого, ни настоящего, ни будущего, потому что всё было бы заранее известно Тао.

Третье утверждение также можно высказать в другом варианте:

Число личностей в любом проявленном мироздании конечно.

Предположим, что проявленное мироздание конечно, а число личностей в нём было бы бесконечным. Тогда всегда имелись бы личности с разными сознаниями, которые ещё не сделали возможного свободного выбора, а значит, и не осознали себя как Тао. Такое мироздание никогда не заканчивалось бы, что противоречит предположению конечности мироздания. Поэтому число личностей, как существ со свободой выбора, в любом проявленном мироздании всегда должно быть конечным.

И наоборот, если предположить, что число личностей в проявленном мироздании всегда конечно, то мироздание тоже должно быть конечным. Бесконечное мироздание состояло бы из бесчисленных возможностей свободного выбора для личностей. Свободный выбор личностей в бесконечном мироздании никогда не заканчивался бы, и личности никогда не смогли бы осознать себя как Тао. Тогда получается, что Тао навсегда лишило бы само себя свободы выбора, проявив свою свободу выбора в личностях. Значит, проявленное мироздание всегда осознаётся Тао как существо, сознание которого составлено из конечного числа всех возможностей, которые могут выбрать личности, чтобы осознать себя как Тао. Так как мироздание и личности не могут проявиться друг без друга, то оба варианта третьего утверждения эквивалентны.

Слово монада в переводе с греческого языка означает «единица» или «единое», и подразумевает неделимость в том смысле, что невозможно отделить нечто от единого целого, чтобы не разрушить единство. Слово индивидуальность в переводе с латинского языка означает «неделимость» и в этом смысле означает то же самое, что и понятие монада. Понятия индивидуальность и монада следует понимать именно в смысле целого, от которого невозможно отделить нечто без того, чтобы не разрушить единство.

Человек осознаёт себя как отдельное существо, как Я. Это означает, что он обладает самосознанием, имеет сознание Я-есть или Я-сознание. Наивысшее Я-сознание имеет Тао, которое неделимо, потому что от него невозможно отделить нечто и, следовательно, оно есть абсолютная индивидуальность. Поэтому истинным Я или истинной самостью человека может быть только абсолютная индивидуальность, которая есть Тао.

Высшее Я человека проявлено в мироздании как его индивидуальность. Индивидуальность человека можно также определить как наивысшее Я-сознание, которое может иметь человек в проявленном мироздании. Чтобы все личности были одинаково свободны, их индивидуальности должны быть потенциально равными. Это возможно, если каждая индивидуальность содержит все возможности свободного выбора личности. Все возможности свободного выбора личности не меняются в проявленном мироздании и, в этом смысле, индивидуальность также не меняется в проявленном мироздании.

Насколько человек осознаёт себя как индивидуальность, определяет его как личность. Человек есть вместе индивидуальность, личность и отношения между иерархиями сознания, проявленные вследствие свободного выбора. Существует древнее знание, что человек состоит из духа, души и тела. Индивидуальность соответствует духу. Личность соответствует душе. Тело соответствует карме, или отношениям иерархий сознания, проявленным вследствие свободного выбора.

Личность определяется сознанием человека и, следовательно, меняется, развиваясь через свободный выбор. Индивидуальность человека есть его высшее проявленное Я, которое неделимо и является принципом личности. Личность нельзя отделить от индивидуальности, так же, как индивидуальность нельзя отделить от человечества. Сознание, которое Тао осознаёт в себе как сознание всех личностей, следует понимать как сознание человечества. Человечество - это не только все личности вместе, но человечество есть существо, сознание которого включает в себя сознание каждой личности. Прежде чем может проявиться отдельная личность, должно проявиться человечество как существо со свободой выбора всех личностей. Когда сознание каждой личности достигает сознания своей индивидуальности, наступает конец мироздания и все личности достигают сознания себя как абсолютной, единой индивидуальности, как абсолютного Я, как Тао. Это есть возвращение индивидуальности, или монады человека, к её источнику - абсолютному Божеству.

Понятия сознание и свобода выбора являются основополагающими для понимания возможности начала и конца проявленного мироздания. Мироздание начинается со свободного выбора Тао проявить в себе личности как существ со свободой выбора. Мироздание существует, пока существует хотя бы одна-единственная личность, которая ещё не достигла осознания себя как индивидуальности в проявленном мироздании. Мироздание заканчивается свободным выбором каждой личности осознавать себя как абсолютную индивидуальность, которая есть Тао. Это возможно только тогда, когда каждый человек уже имеет наивысшее сознание себя как индивидуальности в проявленном мироздании. Только тогда одна личность, как индивидуальность, может осознавать все другие личности, как индивидуальности. Если хоть одна личность ещё не имеет наивысшего сознания себя как индивидуальности, то это означает также, что никакая другая личность не имеет такого наивысшего сознания в силу потенциального равенства индивидуальностей. Поэтому осознание одной личностью себя как Тао может происходить только вместе со всеми другими личностями. Это означает, что ни один человек не может слиться с Тао, то есть осознать себя как Тао, пока другой человек не может слиться с Тао.

Число личностей должно быть конечным в любом проявленном мироздании. Но это число должно быть также различным в различных мирозданиях. Если число личностей в предыдущем и следующем мироздании было бы одним и тем же, то это были бы те же личности в силу потенциального равенства индивидуальностей. Тогда оба мироздания были бы совершенно одинаковыми. Любой выбор был бы не свободным, а заранее известным из предыдущего мироздания, поэтому такое следующее мироздание проявиться не может.

Личности, как разные существа, должны иметь разное сознание. Личности могут иметь один и тот же уровень сознания, но их сознания должны быть различными. Это означает, что в проявленном мироздании всегда существуют личности с более высоким и более низким сознанием. Поэтому также должна существовать личность, имеющая наивысшее сознание себя как индивидуальности, в нашем проявленном мироздании. Это есть та личность, которая в Новом Завете именуется Иисусом Христом. Имя Иисус соответствует сознанию личности, а Христос соответствует сознанию индивидуальности как наивысшему сознанию себя в нашем проявленном мироздании.

Существование свободы выбора личности позволяет задать вопрос, на который не может быть ответа в проявленном мироздании:

Каково число личностей в проявленном мироздании?

Число личностей в проявленном мироздании всегда конечно. Это число известно только бесконечному сознанию Тао, который осознаёт в себе каждую личность как существо со свободой выбора. Чтобы узнать число всех личностей, не нарушая свободы выбора, нужно иметь сознание, которое охватывает все индивидуальности. Сознание всех индивидуальностей может быть достигнуто только всеми личностями вместе. Если все личности уже имели бы сознание себя как индивидуальностей, то все возможности выбора и их последствия были бы уже заранее им известны, и выбор личностей не был бы свободным. Следовательно, свобода выбора личности означает, что личность не может знать конечное число всех личностей в проявленном мироздании. Ответ станет известен всем личностям только тогда, когда каждая личность уже будет иметь наивысшее сознание себя как индивидуальности в проявленном мироздании. Только тогда каждая личность, как индивидуальность, может осознать себя как Тао и может осознать все другие личности как индивидуальности, а значит, и узнать число личностей в проявленном мироздании.

Конечное число личностей есть числовая характеристика мироздания. Оно позволяет дать понятие центра проявленного мироздания. Так как всё имеет сознание, то центром проявленного мироздания будет тот уровень сознания, на котором возможно узнать конечное число личностей в проявленном мироздании. На этом уровне сознания каждая личность осознаёт себя как индивидуальность, и все личности вместе могут осознать себя как абсолютную индивидуальность. Это число находится в основе всех соотношений между иерархиями сознания, независимо от того, возможно ли их выразить в каких-либо числах, или нет. Без конечного числа личностей в проявленном мироздании не может быть проявления мироздания. Без проявленного мироздания не может быть никакой науки. Поэтому знание о существовании конечного числа личностей в проявленном мироздании лежит в основе науки о Тао.


'''
)

itao = {"en":en_itao, "de":de_itao, "ru":ru_itao, }

st.set_page_config(layout="wide")

st.title("☯ iTao ")
#st.title("☯ iTao " + _("I am Tao"))

    
if __name__=='__main__':
#    tab1, tab2 = st.tabs([_("World structure"), _("Involution"),])
#    with tab1:
    st.write(itao[st.session_state.itaolang])
#    with tab2:
#        st.image("images/tao.png")



