'''

https://laotzu.xyz/chapter/display?id=53
https://www.wussu.com/laotzu/laotzu53.html

'''

import streamlit as st
import gettext


localizator = gettext.translation('messages', localedir='locales', languages=[st.session_state.itaolang])
localizator.install() 
_ = localizator.gettext 

en_path = _('''                                                                                                                                                                                
Great Tao (Path) is smooth and plain, yet people prefer the devious bypaths. (Tao Te Ching 道德經 53) 

Modern man loses his waking consciousness during deep dreamless sleep. Initiation leads to the attainment of such waking consciousness which encompasses consciousness of deep dreamless sleep. Thus, initiation leads to the continuity of waking consciousness, and the continuity of waking consciousness means consciousness of the eternal life. The development of consciousness of man in usual life occurs through the development of qualities and faculties. However to become initiate consciously, it is necessary to know methods of the development of qualities and faculties, and to be able to use them properly. As everything is manifested through the hierarchies of consciousness the qualities and faculties of personality depend on what relations will be manifested between personality and the hierarchies of consciousness through free choice of personality. Faculties are determined by how personality can use relations with the hierarchies of consciousness for manifestation of good and evil. How far personality applies faculties for manifestation of good only is determined by qualities, attributes or virtues of personality. Qualities allow personality to counterbalance relations with the hierarchies of consciousness manifested due to the free choice. To be able to manifest only good, it is necessary always to make such free choice that corresponds to the rhythm of the development of consciousness of mankind. Otherwise instead of good will be manifested evil for evil is untimely the good. 

The golden rule

The same faculty could be used for manifestation of good and evil. For example, the faculty of knowledge could be directed on satisfaction of lusts and well-being of all personalities. In order that the development of faculties did not lead to manifestation of evil, it is necessary to take care of the development of qualities. This constitutes the golden rule of the spiritual development:

For every single step that you try to take forwards in having knowledge of hidden truths, take three steps in perfecting your character toward the good. 
    
Conscious development of qualities and faculties leads man to initiation. Consciousness of modern man allows him to pass through the path of initiation without having in his vicinity teacher in physical body, that is, such personality which already attained initiation. There is certain relation between the level of consciousness and qualities. Qualities attained by man on one level of consciousness remain operative on any other level of consciousness. Qualities remain part of consciousness of man also when the rhythm of the development of consciousness is changed. Therefore qualities which were attained in physical body remain part of consciousness of man also after change of consciousness which occurs through death. It is impossible, however, to state the same about all faculties. Faculties to satisfy lusts through physical body are not preserved after death, though lusts remain. Qualities of initiate are natural laws which initiate steadily follows, irrespective of, whether he is incarnated in physical body, or not.  

For there is a natural law for all initiates prompting them not to withhold from man knowledge that is due him. However there is an equally natural law which stating that nothing of esoteric knowledge can be imparted to anyone not called to have it. And the more perfect the initiate, the more strictly these two laws he observes.


The expression natural law does not mean that all initiates make an oath or sign a document to comply with some rules under the fear of punishment. It means that all initiates possess those qualities which allow them to have consciousness of initiate. And to be called to have knowledge or to have access to knowledge means neither more or less than to have qualities of such level of consciousness on which knowledge is used only for good. As any violation of freedom of choice of man is evil, then for initiate will be natural the following third law also:

Regulate each of your actions and each of your words so that free-will decision of any man will not be interfered through you.
    
As present rhythm of the development of consciousness allows each man to become an initiate then some conclusions follow from these laws. First, the path to initiation is opened to any man irrespective of, whether he strives through his free choice to manifest good or evil. Secondly, access to knowledge which man can attain on the path of initiation, depends not so much on his faculties, but rather on his qualities. And thirdly, knowledge attained on the path of initiation, must not violate freedom of choice of any personality. If the path of initiation leads to violation of free choice though one single personality, then this path is the path of black magic. Black magic is such use of beings of the hierarchies of consciousness with objective to achieve satisfaction of one’s own desires and lusts which violate the freedom of choice of man.

Man in physical body, perceiving the world of separate objects, is deprived of direct perception of beings of the hierarchies of consciousness and thus is protected from conscious connection with them. When man enters on the path of initiation, he becomes able not only to perceive beings consciously, but also to control them. Man appears in the unequal position in comparison with other personalities which cannot do this. There appears temptation to take advantage of such possibility for one’s own benefit. The qualities of initiate are guarantee that he will never use means of black magic for achievement of personal objectives. The use of faculties without appropriate development of qualities leads to black magic.

As there are possible various degrees of the development of qualities and supersensible faculties there are various degrees of initiation also. The more qualities of initiate are developed, the higher is level of his consciousness and the higher is degree of his initiation. 

The word teacher will be used further on for the designation of initiate, who possesses qualities that can be characterized as one quality of freedom from egoism. This quality means that personality does not identify itself with its own manifestation and develops the I-consciousness through free choice which corresponds to rhythm of the development of consciousness of mankind. The quality of freedom from egoism is attained, beginning from sixth degree of the initiation, which is called the Sun-Hero. Initiate who reached such level of consciousness is free from earthly Karma and can develop his consciousness without incarnation in physical body on the Earth. If teacher makes free choice to be incarnated in physical body on the Earth, then he does this, following rhythm of the development of consciousness in which new possibilities must be manifested for the development of consciousness of man on the Earth. An example of teacher is Gautama Buddha. Teacher with the highest consciousness who was ever incarnated in physical body is Jesus Christ. Qualities which were developed by Jesus Christ are an ideal for any teacher, because they allowed Jesus Christ to attain the highest consciousness for personality in our world structure. Lucifer possessed the highest faculty of knowledge in the beginning of the evolution, but he had no sufficient qualities to use wisdom for unity of all beings. If Lucifer possessed sufficient qualities, then there would be no his Fall. The legend of Icarus also is confirmation that without developed qualities it is impossible to reach initiation. That Icarus learned to fly, means, that he possessed faculties. The fall of Icarus means, that for achievement of initiation of sixth degree it is not enough to have faculties only. The golden rule is valid on any level of consciousness.

In order to tread the path of initiation, it is enough to make free choice leading to the development of qualities. Long before man chooses the path of initiation, there is already teacher. It is expressed in the ancient saying: When the pupil is ready, the teacher appears. The level of consciousness of teacher is so high, that he is able to inspire disciple, not being incarnated in physical body. Thereby three laws mentioned are always complied with. Waking consciousness of modern man allows him to perceive only one event at once. Teacher is able to perceive several events together at once, and the higher is level of consciousness, the more events teacher is able to perceive at once. Teacher is able to inspire several disciples at once, irrespective of where and in what state of consciousness they are. Therefore teacher has many disciples, as a rule. Disciple going on the path of initiation sooner or later reaches such level of consciousness when he becomes able to perceive teacher. Up to this moment disciple could know nothing about his existence as well. Moreover, man could not know also, that he is already on the path of initiation for a long time. The path of life is already the path of initiation for everyone, whose way of life promotes the development of qualities. For the development of qualities no special conditions of life are necessary. The best conditions for the development of qualities are always those in which man is.

Physical body of man provides protection against direct perception of beings of the hierarchies of consciousness, whose influences are manifested as lusts. The faculty of clairvoyance allows initiate to perceive these beings during lifetime in physical body and his qualities allow him to remain free from their influence. After change of consciousness which is called death every man loses protection of physical body and perception of beings of the hierarchies of consciousness becomes direct experience. If lusts were connected with pleasure received through physical body, then man after death experiences sufferings, to which no sufferings in physical body can be compared, because possibility of satisfaction is absent and lusts as relations with beings of the hierarchies of consciousness still remained. The level of consciousness on which man after death can experience sufferings from his own lusts, is called Kamaloka - place of desire, purgatory.

In Kamaloka man loses that waking consciousness which was limited by perception of the world of separate objects. Instead of the world of separate objects man can perceive in Kamaloka those connections with beings of the hierarchies of consciousness which correspond to his sins. Sin or vice is lack of qualities and is connected with lust. When satisfaction of lust passes into habit, connection with beings becomes sin. Jacob Boehme describes four basic kinds of sin: pride, covetousness, envy, wrath.

Sin is nothing else but relations of consciousness of man with beings of the hierarchies of consciousness manifested through satisfaction of lusts. As man after death has not physical body, then he perceives lusts in Kamaloka as real beings, which have forms reminding physical forms of animals. Consciousness of initiate permeates Kamaloka already during lifetime in physical body, not causing him sufferings because initiate possesses certain degree of the following seven virtues: justice, abstinence from judgment, spiritual strength, cleverness, faith, hope, love.


Manifestation of sin is possible on any level of consciousness. The Fall of Lucifer was caused by pride of his own wisdom. Lucifer had free choice to manifest only those possibilities of choice for personalities in his kingdom, the consequences of which he could himself to become conscious of. Instead of this, the choice was made, which allows personalities to choose from possibilities of rhythm of the development of consciousness directly irrespective of to what consequences this could lead. Thus, personality in the kingdom of Lucifer can manifest good und evil without limitations. As long as the manifested world structure exists, no personality can have perfect qualities. Even personality with the highest consciousness, Jesus Christ, whose qualities it is possible to consider as ideal for all personalities, has no perfect qualities also. There are no restrictions in the development of qualities for personality. Qualities allow personality to manifest good through free choice. However, as there are no restrictions for personality in the development of qualities and manifestation of good, there are no restrictions in the development of sin and manifestation of evil also. Therefore, when one speaks about virtues it is always meant certain degree of the development of qualities. As mankind is one unity, qualities of personality are characteristic of how far personality is conscious of itself to be united with other personalities. Sin is characteristic of how far consciousness of personality is separated from other personalities. As all qualities are connected with each other, because they all correspond to manifestation of good, it is not important, the development of which quality to begin from. The development of one quality leads to the development of other qualities as well.

Qualities and conditions of the occult training

The expression occult training should be understood as training which is not perceived by physical sense organs and in this sense it is hidden, or secret. Nothing is changed for man outwardly when he starts the development of qualities. The attainment of qualities creates conditions which are necessary for the development of supersensible faculties in occult training. As no personality can have perfect qualities, so nobody can satisfy conditions of the occult training perfectly. The chief thing, however, is that man would have perpetual striving for the development of qualities and thus is striving to fulfil conditions of the occult training. Let us consider connection of the development of qualities with conditions of the occult training.

Justice and health

The more man is conscious of himself as member of whole mankind, the more he is conscious of his connection with all personalities and the more he will manifest justice in relation to them. The quality of justice is opposite to the struggle for existence and man, possessing this quality, will not make choice without reckoning with other personalities. Therefore his choice will not assist strengthening of the war of all against all. Striving for satisfaction of the lust of benefit which leads to the war of all against all should not be mistaken for striving to be rich. To be rich in occult language means to possess qualities and faculties, which correspond to qualities. In this sense to be rich in physical life means to possess qualities to attain all what is necessary for the development of consciousness in physical body according to rhythm of the development of consciousness of mankind. The fulfilling of duties in physical life promotes the development of the quality of justice and can be even harmful to personal health. Therefore the first condition of the occult training is health. This means, that man learns to undertake all what is possible for restoration and preservation of health, without refusing from fulfilling of his life duties.

Abstinence from judgement and membership in the whole of life
Any judgement based on personal sympathies and antipathies, means judgement from position of separation from other personalities. All personalities are connected among each other. The higher is consciousness of unity with all personalities, the less is urge to judge on basis of personal sympathies and antipathies. Personal judgement is never ultimately true, because, in order to judge truly it is necessary to have consciousness which encompasses consciousness of all personalities, what it is not possible in the manifested world structure. Ultimately true judgement it is possible only for all personalities together. What single personality can reach in life is never a merit of only one personality. Single personality always uses achievements of other personalities, quite often depriving them of favourable conditions for the development of consciousness. The second condition of occult training will be awareness of oneself as of integral member of mankind and by that as a member of the whole life.

Spiritual strength and reality of thoughts and feelings

Spiritual strength allows man to resist temptations to satisfy lusts. The opposite to strength is weakness which leads to lusts. Man constantly is exposed to temptations in his astral body what is expressed in striving for satisfaction of pleasures, for example, through excessive eating, drinking, sex, possessions and so on. Those who eat too much will manifest lusts in their astral body. All illnesses have their origin in lusts of the astral body. Therefore all religions prescribe purification from lusts through fasting. The concept of fasting should be understood, first of all, as refusal, abstinence from lusts. If man gives no food to physical body, then his physical body will weaken. In similar way, if do not feed lusts with thoughts, feelings, words and deeds, then lusts will be weaken also. However, if man do not takes in food and cherishes, for example, thoughts and feelings of satisfaction of sexual pleasures, then physical body will be destroyed very quickly. Therefore fasting means refusal to give food to lusts. That is why the quality of spiritual strength can be also called as quality of the refusal from lusts. Manifestation of strength and weakness begins with thoughts and feelings of man. Therefore the third condition of the occult training is to be conscious that thoughts and feelings are realities, and have not lesser importance, than words and deeds.

Cleverness and spiritual balance

As no single personality can possess perfect qualities there is always possibility to make a mistake through free choice. However the more the qualities are developed, the less probable is possibility of mistake, because personality makes its choice according to rhythm of the development of consciousness of mankind, instead of according to its own personal urges and objectives. How great the wisdom of one single personality could be, it can be only some part of wisdom of the whole mankind. The quality of cleverness is attained through experience of mistakes. Mistakes are possible on any level of consciousness, therefore manifestation of pride, greed, envy and anger are also possible on any level of consciousness. The quality of cleverness can be called quality of flexibility because it brings previous qualities to harmony and allows personality to become conscious creator of its own destiny. Cleverness promotes fulfilling of fourth condition of the occult training which is called spiritual balance. This means balance between what is inside and outside. Consciousness of the true ‘I’ of man takes place inside human being, but the ‘I’ itself is not only inside, it is everywhere, and human being is part of the ‘I’. Cleverness allows keep balance between requirements of the outer world and inner development of qualities.

Faith and following taken decision
 
Clever, reasonable personality becomes so flexible in the development of its qualities that this allows it to develop quality of faith. The quality of faith means faith of perpetual development of consciousness through free choice which leads to knowledge of the internal infinite source of everything. How perfect an achievement may seem to be, it is only a stage in the development of consciousness of mankind. Any achievement will be always only some semblance of what could be attained. The quality of faith excludes dogmas which are created through personal understanding of religions and religious books. Any religion reflects only a stage on the path of the development of consciousness of mankind. With the changing of consciousness personal understanding of religions and religious books are changing also. Faith allows man to follow taken decision steadily if decision corresponds to rhythm of the development of consciousness of mankind. Following taken decision constitutes fifth condition of the occult training.

Hope and thankfulness

The quality of faith is connected with quality of hope of the development of consciousness through free choice. In what situation personality may be, there is always possibility for it of free choice which leads to knowledge of good. Therefore the sixth condition of the occult training is thankfulness to everything, what personality meets on its path of life. Free life of personality is gift of Tao and it is only possible owing to life of the whole world structure. Free choice of personality could be directed against other personalities, but without the development of its consciousness it is impossible the development of all other personalities, because mankind is one unity. Therefore there is no bad personality. Personality can become evil itself, but this will mean, that evil was necessary for the free development of consciousness of personality through knowledge of evil.    

Love and unity of previous conditions

Love can be manifested only through free choice which leads to unity of all beings. If man makes free choice which leads to compassion, to sympathy, to participation, to unselfish assistance to others, then such free choice also leads to unity of personalities, and, consequently, to unity of all beings. Only personality, which has possibility of free choice to manifest good and evil without any compulsion can manifest love. And the mission of man as personality on the Earth planet is to learn to manifest love. Love must become natural power of man, his striving and his purpose, and could be understood as the power to give without expectation of any return. An example of manifestation of love was given by Jesus Christ. Similar as Jesus Christ was incarnated in physical body in order to help the development of consciousness of mankind on the Earth, personalities with the developed quality of love will be incarnated in the eighth sphere in order to help the development of consciousness of the stayed behind personalities, which became evil itself. Quality of love allows manifest all qualities as one whole. Therefore the seventh condition of the occult training is fulfilling of all previous conditions together.    

There are certain relations between qualities, fulfilling of conditions of the occult training and seven members of man. As all members of man can exist and can be developed in harmony only through the interrelations between each other, then the proper development of qualities and fulfilling of conditions of the occult training can take place only through the interrelations between each other.
     
1. Justice (Health, Physical body)
2. Abstinence from judgement (Membership in the whole of life, Etheric, life body)
3. Spiritual strength (Reality of thoughts and feelings, Astral body)
4. Cleverness (Spiritual balance, ‘I’ (Self))
5. Faith (Following the decision, Self-Spirit, Manas)
6. Hope (Thankfulness, Life-Spirit, Buddhi)
7. Love (Unity of conditions, Spirit-Man, Atman)

Quality of love is quality of sacrifice and giving because man gives his personal richness of qualities and faculties to the development of all beings. In the Gospel of St. Mathew (Matthew 19:16-24.) it is called to enter into the kingdom of heaven, following Jesus Christ.

And, behold, one came and said unto him, Good Master, what good thing shall I do, that I may have eternal life? And he said unto him, Why callest thou me good [perfect]? There is none good [perfect] but one, that is, God: but if thou wilt enter into life, keep the commandments. He saith unto him, Which? Jesus said, Thou shalt do no murder, Thou shalt not commit adultery, Thou shalt not steal, Thou shalt not bear false witness, Honour thy father and thy mother: and, Thou shalt love thy neighbour as thyself. The young man saith unto him, All these things have I kept from my youth up: what lack I yet? Jesus said unto him, If thou wilt be perfect, go and sell that thou hast, and give to the poor, and thou shalt have treasure in heaven: and come and follow me. But when the young man heard that saying, he went away sorrowful: for he had great possessions. Then said Jesus unto his disciples, Verily I say unto you, That a rich man shall hardly enter into the kingdom of heaven. And again I say unto you, It is easier for a camel to go through the eye of a needle, than for a rich man to enter into the kingdom of God.

Jesus Christ speaks first of all about the commandments which lead to eternal life. Man whose consciousness will be preserved after death of physical body will have eternal life. In these commandments it is contained much more, than could be noticed by superficial reading.

The commandment do not murder means do not cause harm or evil to nobody neither to oneself nor to anybody else. It is possible, when free choice of man corresponds to rhythm of the development of consciousness of mankind. If man will learn not to do harm first of all to himself, having cleared himself from lusts, then he also will learn not to do harm to others. To lust after means to strive for pleasure just for sake of pleasure. Therefore the commandment not to commit adultery means do not lust after, and corresponds to continence in the satisfaction of lusts of the astral body. The commandment do not steal corresponds to quality of justice or to compliance with the law of Karma, because fair man is content with that, what it is allowed him to have by his Karma, and the law of Karma is justice. Man who lies, manifests astral beings which destroy his astral body, therefore lie is equivalent to murder on the astral level of consciousness. Father and mother in the commandment honour thy father and thy mother mean not only physical parents. As everything is manifested through the hierarchies of consciousness, man is obliged by his existence first of all to the hierarchies of consciousness without freedom of choice. From this point of view, they also are father and mother of man in the manifested world structure. The respect for the hierarchies of consciousness is developed through comprehension of that, by what man is obliged by them in his life. Then consciousness of man becomes permeated first of all by feeling of thankfulness and he learns to use in his life only that, what is necessary for the development of his consciousness and consciousness of others. If man takes more to himself, than he really needs, then he deprives others of possibility of the development of consciousness. Therefore the commandment honour thy father and thy mother will correspond to the commandment do not be (live) excessive.    

The first five commandments correspond to five vows of Yama: do not kill, do not lie, do not steal, do not be (live) excessive, do not lust after. They were mentioned by Patanjali in his work Yoga-sutras as follows:

Non-killing, truthfulness, non-stealing, continence, and non-receiving, are called Yama.

Continence is interpreted usually as abstinence from waste of sexual energy, and non-receiving - as non-acceptance of gifts and non-accumulation of material possessions. If man wastes his sexual energy because of pleasure this means, that he has lust. If there will be no lust there will be no waste of sexual energy also. Therefore continence means, first of all, do not lust after. Non-receiving does not mean that it is necessary to refuse of use of gifts and material things. Non-receiving means that it is not necessary to take too much and corresponds to the vow do not be (live) excessive.

The correspondence between the commandments of Christianity and the vows of Yama originates from fact that in the life or etheric body of man there are five life currents. They become perceived by each man with certain level of consciousness. Sins, which are opposites to the vows of Yama, act on these life currents destructively. Through destruction of life currents, man kills life in himself. Jesus Christ and Patanjali specify five commandments because they are able to perceive ethetic currents and destructive action of sins on them. The expression to enter into life will mean to enter into consciousness of the life body. In order to become conscious in the life or etheric body, man must first of all comply with vows of Yama. They must become part of consciousness of man. From here it is possible to understand, why Yama is also god of death. For those one, who does not comply with specified commandments, kills life in oneself, gets in the power of god of death and, consequently must die. 

The sixth commandment love thy neighbour as thyself specifies the fact that the development of consciousness of one man depends on the development of consciousness of others. In this commandment it is possible to notice the difference between teaching of yoga and Christianity. The vows of Yama are commandments of the achievement of perfection for single personality. The commandments of Christianity are commandments of the achievement of perfection for all together. The sixth commandment is connected with conceptions of kingdom of heaven and kingdom of God between which there is essential difference. The kingdom of heaven is manifested through the hierarchies of consciousness without freedom of choice. Relations between the hierarchies of consciousness are manifested in rhythms of the development of consciousness of mankind, providing new possibilities of free choice of the development of consciousness to personality. In order that personality could enter into kingdom of heaven, it must make free choice, proceeding not from its own egoism, but from rhythm of the development of consciousness of mankind. Personality becomes then similar to the hierarchies of consciousness. That is called to enter into the kingdom of heaven.

To become perfect and to enter into the kingdom of God means for personality not only to become similar to the hierarchies of consciousness, but also means to include in its own consciousness the consciousness of all hierarchies of consciousness and, thus, to know everything what is possible to know in the manifested world structure. However no personality can become perfect if there is even only one personality which still is not perfect. If though one personality is not perfect, then there is always free choice which is unknown to other personalities. This means that not all is known in the manifested world structure. Therefore conception, that single personality, irrespective of other personalities, can become united with the absolute God, can merge with the Absolute or can attain consciousness of itself as Tao, is a mistake. To enter into the kingdom of God means the same, as to attain consciousness of itself as Tao. For this purpose it is not enough to develop one’s own consciousness by the achievement of richness of qualities and faculties and to enter into the kingdom of heaven. It is necessary to direct the personal richness of qualities and faculties to the development of all. To enter into kingdom of God it is possible only for all personalities together when the richness of every personality becomes property of all.

The occult or secret training is always connected with the development of qualities. In ancient times to the occult training was admitted only those one who already had certain degree of corresponding qualities. As consciousness of man was less developed than it is now, then presence of teacher in the physical body was the necessary condition for the development of supersensible faculties.

The supersensible organs of perception

The development of supersensible faculties is based on the fact, that each time when man develops some virtue or quality, the new faculty of perception which corresponds to quality will be developed also. The development of qualities is connected with the development of astral organs of perception which are called charkas, sacred wheels or lotus flowers. Each man has these organs of perception, however, in order to perceive supersensibly in right manner, it is necessary not only to learn to use organs of perception, but it is necessary that they are properly developed. Skill to use chakras is a faculty. If one makes exercises for the development of chakras without appropriating development of qualities, then attained faculties of supersensible perception will be distorted, and man will fall prey to illusions, accepting what is desirable for real. This occurs because the faculties of perception will be developed through connection with beings of the hierarchies of consciousness from which man becomes dependent. As a rule, man becomes then immoral man striving for satisfaction of not apparently rough, but all the more refined lusts, and his health, both psychic and physical, will be destroyed. The proper development of chakras can occur owing to the development of qualities in every moment of life. For the development of qualities are not necessary neither special conditions, nor specially appointed time, those life conditions which there are now, are also the best.

In Indian writings it is possible to find various methods of the development of chakras. It is necessary to notice, that knowledge about chakras remained secret for a long time, by virtue of danger to get in dependence on beings of the hierarchies of consciousness. Such knowledge was passed over to disciple orally when his consciousness were enough developed. Only when common level of consciousness of mankind was changed, this knowledge could become accessible to every man.

Chakras are astral formations and they are situated in the astral body of man. This always must be considered, when position of chakras will be specified in the area of physical organs of man. Though chakras are single formations, they cannot exist by themselves, and represent one whole. Between chakras there is a plenty of connections, the main of them are called spokes of sacred wheels or petals of lotus flower. For independent development of chakras it is enough to have knowledge about petals of six lotuses. Knowledge about petals of seventh lotus can become actual only when all six chakras are already developed. 
1. Muladhara (Base or Root Chakra, 4 petals)
2. Swadhisthana (Sacral Chakra, 6 petals)
3. Manipura (Solar Plexus Chakra, 10 petals)
4. Anahata  (Heart Chakra, 12 petals)
5. Vishuddha (Throat Chakra, 16 petals)
6. Ajna (Brow or Third Eye Chakra, 2 petals)
7. Sahasrara (Crown Chakra)
    
The proper development of supersensible faculties is connected with purification and strengthening of certain connections between chakras. Lusts are astral formations which weaken and destroy connections between chakras what is manifested in various diseases. Therefore the proper development of chakras begins first of all with redirection of attention from satisfaction of lusts to the development of qualities. Qualities must become natural part of character of man. If man must make conscious efforts in order to live according to qualities, then this mean, that necessarily degree of the development of his qualities is not attained yet.
                                               
The development of qualities and faculties of man occurs through use of forces of thinking, feeling and willing. These forces of soul are interconnected between each other. When man wishes something he manifests feelings to wish and has thoughts about wish. Desire is manifested through free choice, and to make free choice means to manifest the will through Tao. In his day waking consciousness man, as a rule, does not become conscious of connections between these three forces of soul and can not control them consciously. The relations between them are regulated by the hierarchies of consciousness. If man will become conscious of connections between thinking, feeling and willing he will be conscious of the connections between the hierarchies of consciousness, through which these forces of soul are manifested. From here follows the necessity of the development of qualities which allow man to rule over thinking, feeling and willing. These qualities are connected, first of all, with the development of two-petalled, twelve-petalled and sixteen-petalled lotus flower.
Man develops the two-petalled lotus flower when he strives to become conscious of his thoughts, feelings and willing. The striving for conscious control is also that, what it is necessary for the development of this lotus. The development of the twelve-petalled and sixteen-petalled lotus flower has a feature that it is necessary to develop only half of the petals because other petals were developed in previous rhythms of the development of consciousness. 

The development of the twelve-petalled lotus flower 

For the proper development and use of the twelve-petalled lotus, it is necessary to develop the following six qualities:

1. Control of thoughts (Logical consistency of thoughts)
2. Control of actions (Initiative of actions)
3. Endurance, perseverance (Calmness, Equanimity)
4. Forbearance, tolerance (Positivity)
5. Impartiality toward everything that life brings (Faith or trust)
6. Inner balance, equanimity (Harmony)

Control and logical consistency of thoughts

Man gets control over thoughts when he is able to direct the power of thinking to one single object and to hold it on this object. Any object will be suitable and the simpler is the object, the better it will be. Thus the change of thoughts forms logical sequence which corresponds to object. Those outer and inner influences which can cause extraneous thoughts are excluded from consciousness so long until man will not choose to allow them to be a part of his consciousness. The choice of man will remain logical and substantial even if it is influenced from outside by illogical and not concerning object thoughts. Thus all illogical what can reach his consciousness will be transformed into logical sequence. The power of thinking is accustomed to remain under control of man even then, when he begins to perceive beings of the supersensible world and this allows him to remain independent of their influence.

Control and initiative of actions

Man must learn to give similar direction to actions. All actions of man must begin from inner initiative, from conscious free choice. Any action will be brought under control of will. Subsequent actions become logical continuation of previous actions. Conscious ruling of man reaches all deeds both small and great. The will power must remain under control of man also when he meets beings of the supersensible world. Man must be able to follow strictly one’s own will and not to be influenced by beings of the hierarchies. Lusts lose their influence on man and together with this the striving for satisfaction of lust ceases.

Endurance and equanimity

Endurance means that life of feelings is brought to harmony. Man keeps persistence and consistency in achievement of goals he has set himself. No obstacles divert him from goal as long as it is regarded to be the right goal. Obstacles become the requirement for him to overcome them. His feelings remain in harmony what allows him with equal equanimity to meet joy and sorrow, pleasure and unpleasure on his path to the goal. Man reaches certain degree of equanimity and calmness in life of feelings concerning pleasures and sufferings. He does not strive to suppress feelings, but he does not allow them completely to hold sway over his consciousness and degree of their outer manifestation is under his control.
                         
Tolerance and positivity

Forbearance or tolerance towards people and beings allows man to find positivity in all things. Tolerance is connected also with understanding. Evil and good also can coexist because the freedom of choice exists. Evil is only untimely good and result of the manifestation of evil can be transformed into good. Therefore instead of condemnation man strives to understand and to reach positivity in judgements about phenomena of life.
    
Impartiality and faith

Impartial, unbiased man is ready to check up his opinion and view concerning the phenomena of life in every moment. He is always receptive to something new and does not allow the past to predetermine his judgement about new phenomenon in advance. If he has some opinion and corresponding intention, then he also has the power of faith in them. Power of faith allows him to remain opened for any new phenomenon and no obstacles and failures can deprive him of this power. Therefore impartiality means availability of faith.
    
Inner balance and harmony

Inner balance is attained through the harmonious development of previous qualities. Man keeps balance in any situation of life and do not allows neither the highest joy nor the deepest sorrow to deprive him of his inner balance. He attains harmony in inner and outer life and gets ready for the occult training.

The development of the sixteen-petalled lotus flower 

In order to develop the sixteen-petalled lotus flower it is necessary for man to develop consciously the half of the petals also. For this purpose man must attain certain degree of consciousness concerning ideas and conceptions, decisions, words (speech), outer actions, arrangement of life, strivings in life, life experience, inner contemplative life. This degree of consciousness corresponds to the properties of the eightfold path of Buddha which includes: right opinion, right judgement, right word, right course of action, right place, right habits, right memory, right contemplation.

Buddha was first man, who in physical body developed all these properties in himself. 

It is once occurred that in one only man, namely in the personality of Gautama Buddha, all these qualities of the eight-fold path were thorough present. Thereby this personality gave the impulse, that now all men can appropriate these properties to themselves.
    
The objective of the eightfold path is deliverance of man from those connections with beings of the hierarchies of consciousness which were established through lusts and desires in previous incarnations. Lusts and desires make man dependent on beings of the hierarchies of consciousness. This dependence is characterized by the word Samskara. Samskara does not cease to exist through death and it is kept from incarnation to incarnation in physical body. Lusts are rooted in the astral body of man. Therefore to be released from Samskara, man first of all must free his astral body from lusts. Deliverance from Samskara leads to deliverance from necessity of birth in physical body. 
    
The eightfold path leads not only to deliverance from lusts, but also to deliverance from personal desires. Desire is always expressed through his free choice when man strives to attain something. When man would be free from personal desires? Only then when rhythm of the development of consciousness of mankind is manifested in free choice of man. Qualities of the eightfold path allow man to become conscious of possibility to make free choice in which there is no personal desire to attain something. However before to start with the elimination of personal desires, it is necessary to become free from lusts. Otherwise an effort to restrain oneself from desires will to lead to disorder of health.

The degree of the development of qualities
    
The development of qualities must reach such degree, that they become natural part of character of man, become as one whole. The development of character of man begins with free choice which leads to the development of qualities. The consequences of free choice will be relations between the hierarchies of consciousness, manifestation of which will correspond to desirable qualities in man. Free choice must be repeated as long until manifestation of qualities becomes a habit. 

In spiritual science one speaks of four attributes, which must be acquired on the so-called probation path, in order to ascend to the higher knowledge. The first of them is the faculty of discriminating in thoughts between what is true and mere opinion. The second attribute is the right estimation of what is true and real compared against the appearance. The third faculty consists in the exercising of the six attributes already mentioned previously: control of thought, control of actions, perseverance, tolerance, faith and equanimity. The fourth attribute is the love of inner freedom. 
A mere intellectual understanding of what is included in these attributes is of no value. They must be so incorporated into the soul that they establish the inner habits.

All transient outer phenomena which man perceives through physical sense organs are manifestations of relations between the hierarchies of consciousness. Behind these relations there are beings of the hierarchies of consciousness. Fruit and plant which grows from fruit are various manifestations of the hierarchies of consciousness. The hierarchies of consciousness are that true what remains, when the form of phenomena changes. That what is true always exists in basis of the transient phenomenon that is why it is more valuable than phenomenon itself. However that, what is transient, exists for that, what is eternal, and evolution is possible because of existence of that, what is transient. Acting through that, what is transient, man acquires qualities which allow him to have consciousness of that, what is eternal. In order that man could attain inner freedom, it is necessary, that his free choice corresponds to rhythm of the development of consciousness of mankind. Love to inner freedom is love to what is eternal. Eternal, imperishable in man is Tao. Man attaining all the higher levels of the hierarchies of consciousness can reach consciousness of himself as Tao only gradually.

Man who does not strive particularly for the development of supersensible faculties or has no time to develop them, always has possibility of conscious development of qualities in everyday life. Life in physical body is the best school for the development of qualities. It always provides possibility of choice for the development of qualities through use of forces of thinking, feeling and willing. Those one, who through life in physical body develops one's own qualities, will have supersensible organs of perception in correspondence with rhythm of the development of consciousness of mankind.

Qualities of Zodiac

1. Aries ♈ Devotion (reverence) transforms into the power of sacrifice
2. Taurus ♉ Equilibrim (inner balance) transforms into progress
3. Gemini ♊ Perseverance (endurance, steadfastness) transforms into faithfulness
4. Cancer ♋ Unselfishness transforms into catharsis
5. Leo ♌ Compassion transforms into freedom
6. Virgo ♍ Courtesy transforms into tact of the heart
7. Libra ♎ Contentment transforms into serenity
8. Scorpio ♏ Patience  transforms into insight
9. Sagittarius ♐ Control of speech transforms into a sense of truth
10. Capricorn ♈ Courage transforms into the power of redemption
11. Aquarius ♒ Discretion (reticence) transforms into the power of meditation
12. Pisces ♓ Magnanimity transforms into love

Man, who wishes to acquire supersensible faculties still during life in physical body, must develop them through exercises in concentration and meditation. Concentration is to understand here as the directing of attention to certain ideas and concepts which are connected with well-known relations between the hierarchies of consciousness. Meditation is such grasping of feelings, concepts, ideas, thoughts which leads to consciousness of their essence. 

Imagination, inspiration, intuition

Three types of meditation: imagination, inspiration and intuition are most suitable for modern man. As all is manifested through the hierarchies of consciousness, then concepts of three types of meditation can be specified as follows. Imagination is meditation which leads to consciousness of single beings of the hierarchies of consciousness. Meditation which leads to consciousness of relations between beings of the hierarchies of consciousness is inspiration. Intuition is meditation which leads to consciousness of essence of the hierarchies of consciousness. Through intuition man becomes conscious of that, what beings of the hierarchies of consciousness are conscious of and thus he includes consciousness of beings in his consciousness. The exercises in imagination, inspiration and intuition develop use of forces of thinking, feeling and willing. The development of qualities allow to regulate their use so, that man becomes master of three forces of soul, uses them in full consciousness and remains independent from single beings of the hierarchies of consciousness.

Man has possibility to develop faculties and qualities in physical body, and thus he is protected by physical body from direct perception of beings of the hierarchies of consciousness. If man consciously developed qualities in himself, then they remain his property also when he starts to perceive beings of the hierarchies of consciousness directly. Qualities allow him to remain independent of their influences. Man who begins the occult training without sufficient development of qualities, risks to get into dependence on beings, without the slightest idea about such dependence. Only faculties cannot guarantee safety of his freedom.

Here is an example of symbolic images.
From the geometry of Euclid it is known, that the sum of three angles of any triangle is always equal to two right angles. Triangle cannot be drawn or seen by physical eyes because it is impossible to draw or to see with physical eyes line, for line is length without breadth. It is possible to draw an image of triangle however this is not triangle itself. This will be symbolic image which depicts relations between those beings of the hierarchies of consciousness which cannot be seen by physical eyes. Such image of triangle can be evoked mentally in consciousness. If to change angles or sides of triangle mentally, the sum of angles of triangle is kept the same. Then it is possible to imagine equilateral triangle as general image of all possible triangles. It is possible to attach to it feeling of balance and harmony which originates from keeping in consciousness of such image. This will be imagination. Then it is possible to remove image from consciousness and to be aware only of that pure activity of soul which creates such image. This pure activity of soul is connected with relations between the hierarchies of consciousness which are expressed in image of triangle. This will be inspiration. If to keep in consciousness that, what remains after removal of this pure activity of soul, then in consciousness of man will be revealed consciousness of beings of the hierarchies to which corresponds image of triangle. Man has then in consciousness thinking without thoughts generated by pure activity of soul. This will be intuition.

Through intuition it is possible to find out connection of image of equilateral triangle with the mission of the Earth which can be fulfilled by man through establishment of balance between the forces of willing, feeling and thinking. 

In occult symbolism this mission of Earth has always been expressed in a special way by means of a geometrical figure. Amongst geometrical figures you will find none which corresponds to cooperation in a sense of balance so exactly as the equilateral triangle. If you draw an equilateral triangle you will find the three sides are equal, the three angles equal, the vertices are equidistant from each other and all are equidistant from the center. The center of an equilateral triangle is an absolute symbol of activity of balance, so that when the occultist beholds an equilateral triangle he can see in it a symbol of the absolutely balanced cooperation of that, what had the hegemony in three former incarnations of our Earth respectively. The deeds of the ‘I’ in man signify nothing else but the creation of an operative, an active center in nature of man whereby this state of balance can be prepared from within outwards. Man indeed is called to high destiny on our Earth namely to bring about from within outwards, through his whole being, first of all a balance between that what was predominant respectively in various ways and at various times.

The hierarchies of consciousness which are not perceived by physical sense organs constitute the so-called occult writing which could be learned to read and understand. Through imagination man learns to perceive beings of the hierarchies of consciousness in symbolic images. Symbolic images are thereby letters of the occult writing. Inspiration allows man to know the relations between beings of the hierarchies of consciousness and thus to read and understand the occult writing. Intuition allows man himself to have consciousness of the hierarchies of consciousness.

An attainment of the higher level of consciousness in comparison with previous levels always means, that what was carried out by the hierarchies of consciousness on the previous level of consciousness, now man must carry out by himself. In the Vulcan state of consciousness the level of consciousness of man will be so high, that he will be able to form consciously his own kind through himself. Personalities, which stayed behind in the development of consciousness, will be able to develop their consciousness owing to the sacrifice of other personalities. Owing to the faculty to produce his own kind through himself man will provide possibility for personalities in the eighth sphere to be incarnated on the higher level of consciousness. Personalities with high developed consciousness will make free choice to connect the development of their consciousness with the development of consciousness of personalities of the eighth sphere.

The Guardian of the Threshold 
    
Mastering of forces of thinking, feeling and willing makes man able to regulate connections between these forces of soul consciously. If previously the hierarchies of consciousness must provide harmony between them, then on certain level of consciousness man himself must regulate the relations between thinking, feeling and willing. Such level of consciousness man attains through the development of qualities and exercises in imagination, inspiration and intuition. This causes certain changes in relations between consciousness of man and hierarchies of consciousness. The consequences of these changes are that in the etheric body of man are formed three centres of consciousness: in the area of head, throat and heart. These centres of consciousness together with chakras allow man to have consciousness outside physical body. Thus, man reaches the threshold between sensible-physical world and supersensible world. The proper achievement of this threshold is connected with experiences which are called the encounter with lesser and greater Guardian of the threshold.

Before man as a disciple is led to that point at which he can work on his etheric body at will, he must at least, to a certain extent be able to evaluate Karma, be able to achieve self-knowledge. Meditation therefore should not be undertaken without continual self-knowledge, self-observation. By this means will be achieved that at the right moment man will behold the Guardian of the Threshold: the Karma which he has still to wear away. When one reaches this stage being in normal state it merely means nothing else but knowledge of his still available Karma. If I begin to work into my etheric body, I must make it my aim to compensate my still existing Karma.

The lesser Guardian of the threshold is a real being in which the Karma of man is reflected and in which thoughts, feelings and desires are manifested, that do not correspond to rhythms of the development of consciousness of mankind. This is the astral double of man which possesses consciousness and can influence free choice of man. In the astral double are reflected all those connections of man with beings of the hierarchies of consciousness which correspond to his vices. Perception of the lesser Guard of the threshold allows man for the first time to know himself as such as he has made of himself through his free choice. If man attained sufficient degree of the development of qualities in order to pass over to the higher level of consciousness, then from now on he must transform his astral double by himself consciously. If previously the hierarchies of consciousness provided protection against influence of the astral double, then now man must do it himself through control of thinking, feeling and willing. Man endangers to come under influence of the astral double and become dependent on vices which he himself manifested.

If man concedes to influence of the astral double, then his astral consciousness becomes deformed and free choice of man will be influenced from now on by his astral double. If qualities of man are developed high enough and he is able to regulate himself the connections between thinking, feeling and willing, then man has possibility to become conscious of that ideal to which he can direct the development of his consciousness. This is the encounter with the greater Guardian of the threshold. Thoughts, feelings, willing of man on this level of consciousness are real beings, and his further path depends on his free choice weather to strive or not to the attainment of consciousness of the greater Guardian of the threshold. It appears to man as an ideal of consciousness which can be attained if man will follow rhythms of the development of consciousness of mankind. In this ideal are reflected those qualities of Jesus Christ which allowed him to attain the highest consciousness among personalities in the manifested world structure. Thus, the encounter with the greater Guardian of the threshold is the encounter with the Christ.

Man has then free choice to follow the Christ-principle - the principle of union of all personalities. If he chooses not to follow it, then further path of the development of consciousness of man can become even more egoistic, than it was till now. On this path it is possible to find satisfaction of the greatest egoism therefore this path is called the black path. Man who has chosen the black path will stay behind rhythm of the development of consciousness of mankind in the future. It is absolutely not obviously that man will choose to follow the principle of Christ. Through the astral double man becomes accessible to the temptations of satisfaction of personal egoism which are immeasurably exceeded those, which man can encounter in physical body. Before the encounter with the greater Guardian of the threshold man was engaged in the self-perfection. He could develop qualities and faculties and improve his Karma irrespective of what qualities and faculties could develop other personalities. To follow the Christ-principle means to direct all richness of personal qualities and faculties on rendering the assistance in perfection of other personalities. The consequence of following the Christ-principle will be the development of consciousness of personality according to rhythm of the development of consciousness of mankind.

Jesus Christ is integral part of reality. If there is real personality it is possible to become conscious of its existence, to perceive it and, consequently, to encounter with it. Christ cannot be seen with the physical eyes however it is possible to perceive him with supersensible organs of perception. Any system of self-perfection which leads to knowledge of the supersensible reality, will lead to perception of the reality of Jesus Christ also. Any system of self-perfection which leads to proper development of qualities and faculties of man, will also lead to the encounter with the greater Guardian of the threshold. To pass the greater Guardian of the threshold will mean to attain consciousness of freedom from egoism.

One of the most ancient systems of the development of consciousness is yoga. It existed already during the first old Indian culture period. During this period of the development of consciousness of mankind, the relations between physical, etheric and astral bodies of man were different, than they are now. Therefore the system of yoga which Patanjali described in Yoga-Sutras differs from yoga of the first old Indian culture period. Patanjali expounded the stages of the yoga system in such a way that they become suitable to changed consciousness of man. In Yoga-Sutras are described eight stages of yoga:     

Yama, Niyama, Asana, Pranayama, Pratyahara, Dharana, Dhyana, Samadhi are the limbs of Yoga.

Why the yoga system is stated in eight stages, it is possible to understand if to consider, that the development of consciousness of mankind goes through the seven states of consciousness: Saturn, Sun, Moon, Earth, Jupiter, Venus, Vulcan. These states of consciousness correspond to the seven stages of yoga. The eighth stage of yoga is connected with that, that the personalities which have stayed behind in the development of consciousness will form the eighth sphere. In order that the personality could attain the self-perfection, it must attain consciousness of itself as of Tao. However to attain consciousness of oneself as of Tao can only all personalities together. Until there exists the eighth sphere, no personality can reach perfection. The eighth sphere must be transformed into the sphere of perfection. This state of transformation corresponds to the eighth stage of yoga, that unites the previous seven. Thus, in the stages of yoga are contained the preconditions for the achievement of perfection of all personalities together. The highest consciousness of this perfection has Jesus Christ. Therefore the proper development of consciousness according the yoga system will lead also to the encounter with the greater Guardian of the threshold.

During the first old Indian culture period the personality of Christ was known as the Vishva-Karman. In order to perceive Christ during this period man had to be free from the terrestrial Karma and develop his consciousness outside the physical body. In the physical body man who perfected himself through yoga, could perceive with his consciousness other personality which is called Krishna. Consciousness of Krishna is that highest consciousness which man can attain if he will be engaged in self-perfection through the establishment of harmony between the manifestations of three Gunas: Sattva, Rajas and Tamas. Modern man is so connected with luciferic and ahrimanic beings, that he is not capable any more to reach this harmony by himself. After the incarnation of Christ, man in the physical body can reach this harmony of Gunas, if he follows the principle of love manifested through Christ. Only through the help of Christ he can reach the harmony of Gunas. The encounter with the greater Guardian of the threshold becomes the necessity for man striving for the perfection through the yoga.

To understand that, what is meant in yoga system and to know the consequences of the exercises of yoga can only that man who already possesses the certain level of consciousness and faculties of supersensible perception. Therefore for safe development of consciousness by means of the eight stages of yoga it is necessary the presence of the Guru - the teacher in the physical body. Without such Guru the exercises according to the yoga system of Patanjali will lead to the infringements of health. To follow the yoga system of Patanjali there are necessary the direct communication with the Guru and special conditions of life. Therefore independently to follow the yoga system of Patanjali to the modern man it is possible only in exceptional cases.

The Buddhism is another system of self-perfection in which also is provided the possibility of the encounter with the greater Guardian of the threshold. It is possible to find the following words in the text of Dhammapada:

Do not what is evil. Do what is good. Keep your mind pure. This is the teaching of Buddha.

The free choice of man manifests the good or evil, depending on the conformity to the rhythm of the development of consciousness of mankind. When the mind of man is pure, then man is free from lusts and can know intuitively. The pure mind allows man to perceive the rhythm of the development of consciousness of mankind and to make the free choice according to it. As Jesus Christ is the personality with the highest consciousness, then his free choice most of all corresponds to the rhythm of the development of consciousness of mankind. Therefore man with pure mind is able to become conscious of the greater Guardian of the threshold.

Man who properly develops the qualities and faculties of the eightfold path attains consciousness of Buddha. The consciousness of Buddha is consciousness of love and compassion which is free from egoism and the highest consciousness of love and compassion among all personalities has Jesus Christ. Therefore if the encounter with the greater Guardian of the threshold does not occur, then that means that qualities of man are insufficiently developed to attain consciousness of freedom from egoism.

Man may not have the supersensible faculties at all and reach the freedom from egoism during life in the physical body. It is not well known fact, that Mother Teresa (Agnese Gonxhe Bojaxhiu), having passed through the death, has also passed the greater Guardian of the threshold and reached the level of the teacher. She could follow the Christ-impulse during the life in the physical body. To follow the Christ-impulse means, that man leads the life so, that it corresponds to the development of quality of the freedom from egoism and to the consciousness of unity of all people. If to consider the supersensible faculties, which has Gautama Buddha in the physical body, then it is possible to find out, that Mother Teresa had not them. However, if to compare their qualities, it is possible to find them equal, because they were enough to reach the level of the teacher. The way of the development of qualities was different. Gautama Buddha developed the qualities the eightfold path in the solitude through the meditation and contemplation. The development of qualities of Mother Teresa occurred through the help to other people in their everyday life. Both, however, have developed the quality of love and reached the freedom from egoism. Both can be called saint because the concept of saint means that man has the quality of the freedom from egoism. In general, everyone who has reached consciousness of the freedom from egoism, it is necessary to call saint. As concerns the supersensible faculties, then to develop them for man who possesses the qualities, does not makes the great difficulty. Between the births of Gautama Buddha and Mother Teresa in the physical body has passed about 2500 years. During this time interval the qualities of Buddha have received the further development, and he has reached the level of consciousness which exceeds the level of consciousness of Mother Teresa. But if to compare the qualities which Gautama Buddha and Mother Teresa have at the end of their life in the physical body, then their qualities corresponded to the qualities of consciousness of the freedom from egoism. Thus, to have the supersensible faculties is not necessary to attain the new level of consciousness.

The life in physical body always provides the possibilities of the development of qualities of the freedom from egoism. In this sense the best path to the unity of mankind and thus the best way to Tao is the developing of the qualities in everyday life.

'''
)

de_path = _('''                                                                                                                                                                                
Das große Tao (Pfad) ist eben und schlicht, doch die Menschen bevorzugen die verschlungenen Seitenpfade. (Tao Te Ching 道德經 53)

'''
)

ru_path = _('''                                                                                                                                                                                
 Великий Дао (Путь) ровен и прост, но люди предпочитают окольные пути. (Дао Дэ Цзин 道德經 53)

'''
)

path = {"en":en_path, "de":de_path, "ru":ru_path, }

st.title(_("Path"))

st.write(path[st.session_state.itaolang])




