
import streamlit as st
import gettext


localizator = gettext.translation('messages', localedir='locales', languages=[st.session_state.itaolang])
localizator.install() 
_ = localizator.gettext 

en_invol = _('''                                                                                                                                                                                
The Tao begot One.
One begot Two.
Two begot Three.
And Three begot the ten thousand things. (Tao Te Ching 道德經 42)

The freedom of choice of Tao to manifest in itself finite number of personalities was referred to as an infinite cause of emanation of the world structure. Because there is nothing unconscious, this free choice manifests first being, whose consciousness is divine plan, or idea of the development of the world structure. The word idea is used for description of being with finite consciousness which contains all possibilities of manifestation. The separated personalities are not manifested yet and exist as principles of personalities, as individualities. Consciousness of this manifested being is consciousness of all individualities. Consciousness of all individualities that contains all possibilities of free choice of all personalities is consciousness of mankind. To fulfil divine plan, mankind has the freedom of choice of all personalities.

The fulfilment of divine plan occurs in states of involution and evolution. The concept of involution signifies envelopment, folding inwards, and evolution signifies unfolding. Because everything has consciousness, involution signifies envelopment of consciousness, and evolution signifies unfolding of consciousness. Envelopment and unfolding of consciousness are connected with the freedom of choice. The free choice of Tao to become conscious in itself of manifestation of personalities, leads to manifestation of the world structure. Manifestation of consciousness of separated personalities corresponds to involution, because infinite consciousness of Tao is folding into finite consciousness of personalities through free choice of mankind. Free choice of separated personalities in the world structure corresponds to evolution because finite consciousness of personalities is unfolding into infinite consciousness of Tao. Involution and evolution of consciousness are inseparable from the freedom of choice.

So that all personalities are to be manifested equally free, they must themselves determine which consciousness every separately manifested personality will have in order to make its first free choice. This can do only all personalities together, as whole mankind, as one being. If mankind not by itself choose with what consciousness every separated personality will start to make its free choice, then the choice of all personalities, as of whole mankind would be not free and predetermined by Tao from the beginning. Then the first choice of every separately manifested personality would be not free also, what would contradict to the freedom of choice of personality. Therefore, the free choice of Tao to become conscious in itself of manifestation of finite number of personalities manifests mankind, as one being with the freedom of choice of all personalities. This free choice of Tao is called great sacrifice because now only mankind can make free choice through Tao.

The trinity

All conceptions which deserve of attention and which make an attempt to explain manifestation of the world structure refer to necessity of trinity. Therefore, all such conceptions can be characterized by one general statement, expressing the main idea of the emanation of the world structure:

One manifests Two; Two manifest Three; Three manifest the world structure.

The emanation of the world structure from and in Tao is possible because an object which Tao is conscious of in itself has consciousness and becomes subject of consciousness. Herein it is included possibility that manifested One becomes Two. However, One must be manifested first before Two can be manifested. Manifested One is not Tao because Tao is infinite, and something manifested can be only a being with finite consciousness. Manifested One can contain only one manifested world structure and only finite number of personalities in its finite consciousness. Infinite consciousness of Tao contains all countless possibilities of manifestation of the world structures and personalities.

Manifestation of One, as being with finite consciousness, begins with free choice of Tao to become conscious in itself of finite number of personalities. The result of such consciousness is manifestation which itself has consciousness and which is called mankind. This is manifested One. 

To manifest something it is possible only through the free choice. In order to make free choice, it is necessary to have the freedom of choice. Therefore, the freedom of choice must exist in all three elements of the trinity, so that the world structure could be manifested, in which finite number of personalities have freedom of choice. Because mankind is always first manifested being with freedom of choice of all personalities, it is possible to make the following statement:

Free mankind, which is conscious of itself as Unity is One.

Mankind has divine plan of the development of all possibilities of consciousness of personalities in itself. Which number of personalities must be manifested is predetermined through free choice of Tao in advance. All possibilities of any choice of personalities are also predetermined through individualities in advance. However, which relations of consciousness will be manifested between personalities, which consciousness will have every separately manifested personality, all personalities must determine together, as one whole mankind.

Manifestation of separated personalities can occur only together with manifestation of hierarchies of consciousness without freedom of choice. So that equally free personalities and hierarchies of consciousness without freedom of choice, as all possibilities of free choice of personalities, have to be manifested, it is necessary that whole mankind is conscious of duality in itself. One element of duality must correspond to all personalities with freedom of choice, and another element of duality must correspond to all hierarchies of consciousness without freedom of choice. Possibility for mankind to become conscious in itself of duality exists, as consequence of self-consciousness. Mankind cannot be not conscious of duality in itself because it has self-consciousness, mankind, however, has freedom to choose how to be conscious of duality in itself. To become conscious in itself of duality it is necessary for manifestation of the world structure. However, mankind makes its free choice to determine which relations will be manifested between elements of duality.

The free choice of mankind as One allows to become conscious of such possibilities of manifestation of all relations between two elements of duality which are most suitable for manifestation of separated free personalities. Such free choice is made from knowledge of all possibilities of free choice of all personalities. The free choice of mankind as One, allows mankind to become conscious of itself as Two. Personalities and hierarchies of consciousness exist in consciousness of mankind as two original principles. Hence, the following statement:

Free mankind, which is conscious of itself as Duality is Two.

To become conscious in itself of duality it is not enough for manifestation of plenty of  beings in the world structure yet. For this purpose it is necessary that mankind becomes conscious of trinity in itself. The possibility to become conscious of the trinity in itself exists because mankind does not lose consciousness of itself as One. Mankind is conscious of itself as One and as Two together. To be conscious of itself as One and as Two together means to become conscious of itself as Three. Mankind makes free choice of which relations of consciousness will be manifested between the elements of trinity. Therefore, it is possible to make one more statement:

Free mankind, which is conscious of itself as Trinity is Three.

Involution of consciousnesses of mankind occurs through free choice of mankind as one being, consisting of all individualities. All individualities are potentially equal and contain all possibilities of free choice of all personalities. Involution of consciousness consists of that, that mankind becomes conscious in itself of principles or ideas that can be manifested in evolution beside each other and in each other. The purpose is manifestation of separated personalities with freedom of choice and of hierarchies of consciousness without freedom of choice. 

Mankind becomes conscious of itself as One, Two and Three together. The state of consciousness as One is attained together with state of consciousness as Two and together with state of consciousness as Three.  Therefore all states of consciousness exist always together, in each other and beside each other. This means Three are One. 

There are no contradictions between spiritual science and ancient scriptures. Ancient writings, however, do not refer to the freedom of choice directly. The reason for it is that waking consciousness of man was not developed so far yet, that it was possible to speak about freedom of choice directly. Therefore ancient scriptures mention the freedom of choice indirectly. Consciousness of man, however, has changed. Responsibility of personality for its free choice changes accordingly to its consciousness. To point out to the freedom of choice became necessary because further destiny of mankind on the Earth depends on that, that every single personality will become conscious of consequences of its free choice.

The mutual existence of three states of consciousness of mankind as One, Two and Three leads to further involution of principles of consciousness, life and form. From any three elements (a, b, c), without consideration of their order, it is possible to form only seven different combinations (a, b, c, ab, bc, ac, abc). Therefore, consciousness by which mankind becomes conscious of trinity determines sevenness of consciousness. Mankind becomes conscious of trinity in itself and through trinity becomes conscious of itself, what creates seven combinations of consciousness. Free choice of mankind determines which relations of consciousness will be manifested between all possible combinations of consciousness of trinity. The result of free choice of mankind is seven combinations of consciousness of trinity, or seven principles. 

These seven principles must be think of as the existing beings; as the relationships of consciousness of trinity, manifested in seven essential forms of consciousness.

1. a - All Might
2. b - All Wisdom
3. c - All Love
4. ab - All Justice
5. bc - All Redemption
6. ac - All Hallowing
7. abc - All Harmony

The world structure will be manifested when plenty of hierarchies of consciousness will be manifested. This occurs whilst mankind becomes conscious of plenty of principles in itself. Mankind becomes conscious of itself as One, Two, Three and so on. Further involution of consciousness occurs whilst mankind becomes conscious of sevenness, or of seven creative spirits before the throne of God. 

Before seven spirits of God can be manifested during evolution, they all must become conscious to mankind as principles during involution. Because single personalities are not manifested yet, involution of consciousness of mankind occurs through free choice of whole mankind, and not through free choice of single personalities. The result of such mutual free choice of mankind, are principles of consciousness, life and form. Mankind becomes conscious of principles in itself which can be manifested as beings with self-consciousness. Beside principles with lower consciousness mankind becomes conscious of principles with higher consciousness in itself. In such a way, involution of consciousness of mankind is involution of principles. 

Consciousness of modern man in physical body allows him to make distinction between space and time. Awareness of space is connected with manifestation of different relations between hierarchies of consciousness beside each other and in each other. Successive repetition of changes of relations between hierarchies of consciousness following one after another, leads to awareness of time. Personalities can become conscious of space and time only together with manifestation of hierarchies of consciousness. In this sense involution of consciousness of mankind is also process of wrapping up of infinite consciousness of Tao into space and time. In state of involution personalities and hierarchies of consciousness have no independent existence yet because they are only parts of consciousness of mankind. Therefore, the state of involution of consciousness of mankind is timeless and spaceless. Time and space will be manifested only in the state of evolution and exist beside each other and in each other. 

The purpose of involution of consciousness of mankind is manifestation of single personalities which are able to make their free choice. Evolution of consciousness of personalities begins with manifestation of single personalities. Because involution and evolution of consciousness are inseparable from the freedom of choice, they cannot exist without each other also. The free choice of mankind in state of involution leads to free choice of personalities in state of evolution. The change of two states of consciousness, such as for example, involution and evolution is rhythm, or cycle of consciousness.

The rhythms

In any rhythm or cycle there are always two alternating states as result of principle of duality. These two states can be considered as two opposites. Because there is nothing unconscious, rhythm can be defined as alternation or change of two states of consciousness. Such events as day and night, in-breathing and out-breathing, yin and yang and so on, are rhythms of consciousness also.

Esoteric philosophy of all times describes life of the world structure, as rhythmic life. Indian philosophy, for example, speaks of inhalation and exhalation of One. The One experiences different states of its divine life. These states are compared to in-breathing and out-breathing. Out-breathing of the One corresponds to manifestation of the world structure from Tao and in-breathing corresponds to state of dissolution of the world structure in Tao. Thus alternate the manifested and not manifested world structure, states of activity and rest. Manvantara is state of activity and Pralaya is the state of the One, resting in himself.

Basic or main rhythm of the world structure is determined by two states of consciousness, by the state of consciousness where Tao is conscious in itself of personalities, as beings with freedom of choice, and by state of consciousness where all personalities are conscious of themselves as Tao. This corresponds to manifestation of the world structure from Tao and to dissolution of the world structure in Tao. It is necessary to emphasize again that manifestation of any rhythm is result of free choice. The main rhythm is result of free choice of Tao to be conscious of finite number of personalities in itself as well as result of the free choice of all personalities to become conscious of themselves as Tao.

The numerical characteristic of this rhythm is finite number of personalities in the manifested world structure. Because manifestation of finite number of separated personalities occurs only after completion of involution of consciousness of mankind, all rhythms that could be manifested in the world structure must become conscious to mankind in state of involution. Because in the world structure must be manifested personalities with the freedom of choice and hierarchies of consciousness without freedom of choice, all rhythms must be manifested through hierarchies of consciousness without freedom of choice. In state of involution mankind becomes conscious of different rhythms of consciousness, life and form which all separated personalities must experience during involution in order to become conscious of themselves as Tao.

The state of involution of consciousness of mankind is timeless and spaceless. Space and time are manifested only in state of evolution. Evolution of consciousness of personalities occurs in space and time. Involution and evolution together form creative activity of the manifested world structure. According to Indian philosophy the creative cycle of activity must be replaced by creative inactivity in which manifested world structure is dissolved in Tao. Besides, it is mentioned that states of creative activity - Manvantara and inactivity - Pralaya have same duration.

In state of involution all personalities create no Karma yet, but free choice of mankind prepares conditions for free choice of separated personalities in evolution. Karma can be created by single personalities only in state of evolution. Therefore, state of involution can be compared with state of Pralaya, and state of evolution with state of Manvantara.

It is necessary to point out to certain difficulty which arises already by comparison of duration of involution and evolution. Involution occurs prior to manifestation of time and space. Evolution occurs in time and space. It is possible to compare only by units of time and space. Such units of comparison are rhythms which are manifested only in state of evolution. However in state of involution rhythms are not manifested yet, neither time nor space is manifested, therefore, it is impossible to compare duration of involution and evolution. Nevertheless it is possible to claim that all rhythms which mankind became conscious of in state of involution will become conscious to separated personalities in state of evolution. And in this sense it is possible to claim that involution and evolution have equal duration.

Still bigger difficulty arises by attempt to compare duration of state of the manifested world structure and duration of state in which the world structure is dissolved in Tao. Such state is also called Maha-Pralaya in Indian philosophy. Is it possible to compare the state of infinite loneliness and oneness of Tao in rhythms of the manifested world structure whose source is Tao? Indian philosophy, for example, specifies duration of our world structure in terrestrial years and equates their number to duration of Maha-Pralaya. 

Similar calculations could be found in the second volume of Secret Doctrine where the number equal to 311 040 × 10⁹ terrestrial years is given. Although various calculations can differ from each other, their sense remains the same. All calculations express duration of the world structure in finite number of terrestrial years and equate it to the state of Maha-Pralaya when no world structure is manifested, when Tao dwells in its infinite loneliness and oneness.

If to suppose Tao dwells in its infinite loneliness and oneness exactly as much terrestrial years as the world structure can last, then it would mean Tao is subjected to some rhythm. Tao is source of any rhythm and can not be subjected to rhythm. May Tao, who is always conscious in itself of all possibilities of manifestation of all world structures, to be in need of such state whose duration could be measured by finite number of terrestrial days, before next world structure is manifested? If Tao is always conscious of all possibilities of manifestation of next world structure, then the state of Maha-Pralaya could pass over into state of involution at once. Even if certain pause existed between the end of preceding world structure and the beginning of next world structure, it would be impossible to measure it by units of the manifested world structure. Therefore, any such calculations can be only characteristics of the manifested world structure. In this sense that number of the terrestrial years is characteristics of number of rhythms which every personality must experience in order to become conscious of itself as Tao.

However between the states in which the world structure is manifested and is not manifested, there always exist relations to which it is possible to point out. On the one hand, in not manifested world structure all possible results of free choice are known to Tao, but free choice itself cannot be made by single personalities, because they are not manifested yet. On the other hand, in the manifested world structure, all possible results of any free choice are unknown to personalities, but free choice itself can be made. These two sides express relations which can be considered equal for manifested and not manifested world structure. These relations always exist because in infinite consciousness of Tao always exist possibilities of manifestation of new world structures.

The world structure comes to an end when every personality becomes conscious of itself as Tao. Only then the finite number of personalities can become known to every personality in the manifested world structure. Therefore, no being in the manifested world structure can know what the next world structure will be. There is no possibility to compare the present and next world structures because it is not known what may be manifested in next world structure. It is possible, however, to state, that next manifested world structure never repeats itself because the number of personalities is always different in any world structure. Next world structure cannot contain something that was already recognized by personalities through free choice in uncountable preceding world structures. Otherwise it would be known to Tao in advance which choice personalities will make and such choice would not be free. The true ‘I’ or Self of personality is Tao. Therefore, the ‘I’ of man was always manifested in personalities in preceding world structures and always will be manifested in personalities in following world structures. Knowledge about preceding and next world structure is beyond consciousness of single personality in the manifested world structure. 

Free choice of mankind in state of involution leads to further awareness of mankind of principles of consciousness, life and form. The state of involution is purely internal state where nothing is manifested externally yet, and everything what will be manifested is in consciousness of mankind. Neither principles, nor single personalities have independent existence yet. Principles get independent existence together with the manifestation of single personalities. Manifestation of single personalities signifies beginning of evolution. On transition from involution to evolution mostly lowest state of principles of consciousness, life and form is attained. This lowest state is always higher than any state of evolving single personalities and principles. 

'''
)

de_invol = _('''                                                                                                                                                                                
Das Tao brachte das Eine hervor.
Das Eine brachte das Zwei hervor.
Das Zwei brachte das Drei hervor.
Und das Drei brachte die zehntausend Dinge hervor. (Tao Te Ching 道德經 42)

Es wurde auf die Wahlfreiheit des Tao, in sich die endliche Anzahl der Persönlichkeiten zu manifestieren, als die unendliche Ursache der Emanation des Weltgebäudes verwiesen. Da es nichts Unbewusstes gibt, manifestiert diese freie Wahl die erste Wesenheit, deren Bewusstsein der göttliche Plan oder die Idee der Entwicklung des Weltgebäudes ist. Das Wort Idee wird für die Bezeichnung der Wesenheit mit dem endlichen Bewusstsein, das alle Möglichkeiten der Manifestation enthält, verwendet. Die einzelnen Persönlichkeiten sind noch nicht manifestiert und existieren als die Prinzipien der Persönlichkeiten oder als die Individualitäten. Das Bewusstsein dieser manifesten Wesenheit ist das Bewusstsein aller Individualitäten. Das Bewusstsein aller Individualitäten, das alle Möglichkeiten der freien Wahl der Persönlichkeiten enthält, ist das Bewusstsein der Menschheit. Um den göttlichen Plan zu erfüllen, besitzt die Menschheit die Wahlfreiheit aller Persönlichkeiten.

Die Erfüllung des göttlichen Planes geschieht in den Zuständen von Involution und Evolution. Der Begriff Involution bedeutet Einhüllung, Evolution bedeutet Entfaltung. Da alles ein Bewusstsein hat, bedeutet Involution die Einhüllung des Bewusstseins und Evolution die Entfaltung des Bewusstseins. Einhüllung und Entfaltung des Bewusstseins sind mit Wahlfreiheit verbunden. Die freie Wahl des Tao, sich der Manifestation der Persönlichkeiten in sich bewusst zu werden, führt zur Manifestation des Weltgebäudes. Die Manifestation des Bewusstseins der einzelnen Persönlichkeiten entspricht der Involution, da das unendliche Bewusstsein des Tao in das endliche Bewusstsein der Persönlichkeiten durch die freie Wahl der Menschheit eingehüllt wird. Die freie Wahl der einzelnen Persönlichkeiten im Weltgebäude entspricht der Evolution, weil das endliche Bewusstsein der Persönlichkeiten in das unendliche Bewusstsein des Tao entfaltet wird. Involution und Evolution des Bewusstseins sind von der Wahlfreiheit untrennbar.

Damit alle Persönlichkeiten gleich frei manifestiert werden, müssen sie selbst bestimmen, welches Bewusstsein jede einzelne manifestierte Persönlichkeit haben wird, um ihre erste freie Wahl zu treffen. Dies können nur alle Persönlichkeiten zusammen als die gesamte Menschheit  als eine Wesenheit. Wenn die Menschheit nicht selbst wählen würde, mit welchem Bewusstsein jede einzelne Persönlichkeit ihre freie Wahl zu treffen beginnen wird, wäre die Wahl aller Persönlichkeiten als der ganzen Menschheit gleich von Anfang an nicht frei, sondern vom Tao vorbestimmt. Dann wäre die erste Wahl jeder unterschiedlich manifestierten Persönlichkeit auch nicht frei, was der Wahlfreiheit der Persönlichkeit widersprechen würde. Deshalb manifestiert die freie Wahl des Tao, sich der Manifestation der endlichen Anzahl von Persönlichkeiten in sich bewusst zu werden, die Menschheit als eine Wesenheit mit Wahlfreiheit aller Persönlichkeiten. Diese freie Wahl des Tao nennt man das große Opfer, da jetzt nur die Menschheit die freie Wahl durch den Tao treffen kann.

Die Dreiheit

Alle Konzeptionen, die Aufmerksamkeit verdienen und die den Versuch machen, die Manifestation des Weltgebäudes zu erklären, verweisen auf die Notwendigkeit der Dreiheit. Deshalb können alle diese Konzeptionen mit einen allgemeinen Behauptung, die die Hauptidee der Emanation des Weltgebäudes ausdrückt, charakterisiert werden:

Eine manifestiert Zwei; Zwei manifestieren Drei; Drei manifestieren das Weltgebäude.

Die Emanation des Weltgebäudes aus dem Tao und im Tao ist möglich, weil ein Objekt, das dem Tao in sich bewusst ist, ein Bewusstsein hat und ein Subjekt des Bewusstseins wird. Darin ist eine Möglichkeit enthalten, dass die manifeste Eine zur Zwei wird. Aber bevor die Zwei manifestiert werden kann, muss zuerst die Eine manifestiert sein. Die manifeste Eine ist nicht Tao, da Tao unendlich ist, und manifestiert kann nur eine Wesenheit mit endlichem Bewusstsein sein. Das manifeste Eine kann in seinem endlichen Bewusstsein nur ein manifestes Weltgebäude und nur eine endliche Anzahl von Persönlichkeiten enthalten. Das unendliche Bewusstsein des Tao beinhaltet alle unzähligen Manifestationsmöglichkeiten der Weltgebäude und Persönlichkeiten.

Die Manifestation des Einen als eine Wesenheit mit endlichem Bewusstsein beginnt mit der freien Wahl des Tao, sich der endlichen Anzahl der Persönlichkeiten in sich bewusst zu sein. Das Ergebnis dieses Bewusstwerdens ist die Manifestation, die ein Bewusstsein hat und die als Menschheit genannt istt. Dies ist das manifeste Eine.

Etwas zu manifestieren ist nur durch die freie Wahl möglich. Um eine freie Wahl zu treffen muss man Wahlfreiheit haben. Deshalb muss in allen drei Elementen der Dreiheit die Wahlfreiheit vorhanden sein, damit das Weltgebäude, in dem die endliche Anzahl der Persönlichkeiten die Wahlfreiheit haben, manifestiert sein kann. Da die Menschheit immer die erste manifestierte Wesenheit mit Wahlfreiheit aller Persönlichkeiten ist, ist folgende Behauptung möglich:

Die freie Menschheit, die sich selbst als Einheit bewusst ist, ist Eine.

Die Menschheit trägt in sich den göttlichen Plan der Entwicklung aller Möglichkeiten des Bewusstseins der Persönlichkeiten. Welche Anzahl der Persönlichkeiten manifestiert sein muss, ist durch die freie Wahl des Tao im Voraus bestimmt. Alle Wahlmöglichkeiten der Persönlichkeiten sind auch durch die Individualitäten im Voraus bestimmt. Welche Bewusstseinsbeziehungen jedoch zwischen den Persönlichkeiten manifestiert werden, welches Bewusstsein jede unterschiedlich manifestierte Persönlichkeit haben wird, müssen alle Persönlichkeiten zusammen als die ganze Menschheit bestimmen.

Die Manifestation der einzelnen Persönlichkeiten kann nur zusammen mit der Manifestation der Hierarchien des Bewusstseins ohne Wahlfreiheit geschehen. Damit die gleich freien Persönlichkeiten und die Hierarchien des Bewusstseins ohne Wahlfreiheit als alle Möglichkeiten der freien Wahl der Persönlichkeiten manifestiert sind, ist es notwendig, dass die ganze Menschheit sich der Zweiheit in sich bewusst wird. Ein Element der Zweiheit muss allen Persönlichkeiten mit Wahlfreiheit, und das andere Element der Zweiheit allen Hierarchien des Bewusstseins ohne Wahlfreiheit entsprechen. Die Möglichkeit der Menschheit, sich der Zweiheit in sich bewusst zu werden, existiert als Konsequenz des Selbstbewusstseins. Die Menschheit kann sich der Zweiheit in sich nicht nicht bewusst sein, da sie Selbstbewusstsein besitzt, dennoch hat die Menschheit aber die Wahlfreiheit, wie sie sich der Zweiheit in sich bewusst wird. Sich der Zweiheit bewusst zu sein, ist für die Manifestation des Weltgebäudes notwendig, aber die Menschheit hat die freie Wahl, zu bestimmen, welche Beziehungen zwischen den Elementen der Zweiheit manifestiert sein werden.

Die freie Wahl der Menschheit als Eines erlaubt es der Menschheit, sich jener Manifestationsmöglichkeiten der Beziehungen zwischen den beiden Elementen der Zweiheit bewusst zu werden, die am besten für die Manifestation der einzelnen freien Persönlichkeiten geeignet sind. Diese freie Wahl wird aus dem Wissen aller Möglichkeiten der freien Wahl der Persönlichkeiten getroffen. Die freie Wahl der Menschheit als Eines erlaubt es der Menschheit, sich als Zwei bewusst zu werden. Die Persönlichkeiten und die Hierarchien existieren im Bewusstsein der Menschheit als zwei Ursprungsprinzipien. Die Bezeichnungen dieser Prinzipien in Sanskrit lauten Purusha und Prakriti. Dies entspricht der Manifestation des Sohnes durch den Vater oder der Zwei durch das Eine. Daraus folgt die Behauptung:

Die freie Menschheit, die sich selbst als Zweiheit bewusst ist, ist das Zwei.

Sich in sich der Zweiheit bewusst zu werden, ist nicht ausreichend für die Manifestation einer Menge von Wesenheiten im Weltgebäude. Dazu ist es notwendig, dass die Menschheit sich der Dreiheit bewusst wird. Die Möglichkeit für die Menschheit, sich in sich der Dreiheit bewusst zu werden, existiert, weil die Menschheit das Bewusstsein von sich selbst als Eines nicht verliert. Die Menschheit ist sich selbst als Eines und als Zwei zusammen bewusst. Sich selbst als Eines und Zwei bewusst zu sein, bedeutet, auch sich selbst als Drei bewusst zu werden. Die Menschheit trifft die freie Wahl, welche Bewusstseinsbeziehungen zwischen den Elementen der Dreiheit manifestiert sein werden. Deshalb lässt sich eine weitere Behauptung aufstellen:

Die freie Menschheit, die sich selbst als Dreiheit bewusst ist, ist Drei.

Die Involution des Menschheitsbewusstsein geschieht durch die freie Wahl der Menschheit als einer Wesenheit, die aus allen Individualitäten besteht. Alle Individualitäten sind potentiell gleich und enthalten alle Möglichkeiten der freien Wahl der Persönlichkeiten. Die Involution des Bewusstseins besteht daraus, dass die Menschheit sich der Prinzipien oder der Ideen, die in der Evolution nebeneinander und ineinander manifestieren sein können, in sich bewusst wird. Das Ziel ist die Manifestation der einzelnen Persönlichkeiten mit Wahlfreiheit und der Hierarchien des Bewusstseins ohne Wahlfreiheit.

Die Menschheit wird sich von sich selbst als Eines, als Zwei und als Drei zusammen bewusst. Der Zustand des Bewusstseins von Einem wird zusammen mit dem Zustand des Bewusstseins von Zwei und zusammen mit dem Zustand des Bewusstseins von Drei erreicht. Deshalb existieren alle Bewusstseinszustände immer zusammen, ineinander und nebeneinander. Dies bedeutet, dass die Drei Eines sind. 
 
Zwischen der Geisteswissenschaft und den altertümlichen Schriften gibt es keine Widersprüche. Die alten Schriften verweisen jedoch nicht direkt auf die Wahlfreiheit. Der Grund dafür ist, dass das Wachbewusstsein des Menschen noch nicht soweit entwickelt war, um von der Wahlfreiheit offen reden zu können. Deshalb sprachen die altertümlichen Schriften die Wahlfreiheit nur indirekt an. Das Bewusstsein des Menschen hat sich aber geändert. Die Verantwortung einer Persönlichkeit für ihre freie Wahl ändert sich entsprechend ihres Bewusstseins. Es ist notwendig geworden, auf die Wahlfreiheit direkt hinzuweisen, denn davon, dass jede einzelne Persönlichkeit sich der Folgen ihrer freien Wahl bewusst wird, hängt das weitere Schicksal der Menschheit auf der Erde ab.

Die gemeinsame Existenz von drei Zuständen des Menschheitsbewusstseins als Eins, Zwei und Drei führt zur weiteren Involution der Bewusstseinsprinzipien von Leben und Form. Aus beliebigen drei Elementen (a, b, c) kann man ohne Berücksichtigung ihrer Reihenfolge nur sieben verschiedenen Kombinationen bilden (a, b, c, ab, bc, ac, abc). Deshalb bestimmt das Bewusstsein, mit dem die Menschheit sich der drei Gunas bewusst wird, die Siebenheit des Bewusstseins. Die Menschheit wird sich der Dreiheit in sich und durch die Dreiheit sich selbst bewusst, was sieben Kombinationen des Bewusstseins bildet. Die freie Wahl der Menschheit bestimmt, welche Bewusstseinsbeziehungen zwischen den möglichen Bewusstseinskombinationen der drei Gunas manifestiert werden. Das Ergebnis der freien Wahl der Menschheit sind die sieben Bewusstseinskombinationen der Dreiheit oder sieben Prinzipien.

Diese sieben Prinzipien sind als die existierenden Wesenheiten zu denken – als die Bewusstseinsverhältnisse von Dreiheit, die sich in sieben wesentlichen Bewusstseinsformen manifestieren.

1. a - Allmacht
2. b - Allweisheit
3. c - All-Liebe
4. ab - Allgerechtigkeit
5. bc - Allerlösung
6. ac - Allheiligung
7. abc - Allseligkeit

Das Weltgebäude wird manifestiert, wenn eine Menge der Hierarchien des Bewusstseins manifestiert ist. Dies geschieht, indem die Menschheit sich in sich einer Menge von Prinzipien bewusst wird. Die Menschheit wird sich selbst als Eines, als Zwei, als Drei und so weiter bewusst. Die weitere Involution des Menschheitsbewusstseins geschieht, indem die Menschheit sich der Siebenheit oder der sieben schöpferischen Geister vor dem Throne Gottes bewusst wird.

Bevor die sieben Geister des Gottes und die einundzwanzig Prajapatis während der Evolution manifestieren sein können, müssen sie der Menschheit während der Involution als die Prinzipien bewusst werden. Da die einzelnen Persönlichkeiten noch nicht manifestiert sind, geschieht die Involution des Menschheitsbewusstseins durch die freie Wahl der ganzen Menschheit und nicht durch die freie Wahl der einzelnen Persönlichkeiten. Das Ergebnis dieser gemeinsamen freien Wahl der Menschheit sind die Prinzipien von Bewusstsein, Leben und Form. Die Menschheit wird sich der Prinzipien, die als Wesenheiten mit Selbstbewusstsein manifestiert sein können, in sich bewusst. Neben den Prinzipien mit höherem Bewusstsein werden der Menschheit dabei auch die Prinzipien mit niedrigerem Bewusstsein bewusst. Auf diese Weise ist die Involution des Menschheitsbewusstseins eine Involution der Prinzipien.

Das Bewusstsein des modernen Menschen im physischen Körper erlaubt es, zwischen Raum und Zeit zu unterscheiden. Sich des Raumes bewusst zu sein ist verbunden mit der Manifestation von verschiedenen Beziehungen zwischen den Hierarchien des Bewusstseins nebeneinander und ineinander. Eine Wiederholung von aufeinander folgenden Veränderungen der Beziehungen zwischen den Hierarchien des Bewusstseins führt zum Bewusstsein, mit dem man sich der Zeit bewusst wird. Die Persönlichkeiten können sich Raum und Zeit nur zusammen mit der Manifestation der Hierarchien des Bewusstseins bewusst werden. In diesem Sinne ist die Involution des Menschheitsbewusstseins auch ein Prozess des Einhüllens des unendlichen Bewusstseins des Tao in Raum und Zeit. Im Involutionszustand haben die Persönlichkeiten und die Hierarchien des Bewusstseins noch kein selbständiges Dasein, weil sie nur Teile des Menschheitsbewusstseins sind. Deshalb ist der Involutionszustand des Menschheitsbewusstseins zeitlos und raumlos. Zeit und Raum werden nur im Evolutionszustand  manifestiert sein und existieren nebeneinander und ineinander.

Das Ziel der Involution des Menschheitsbewusstseins ist die Manifestation der einzelnen Persönlichkeiten, die in der Lage sind, ihre freie Wahl zu treffen. Mit der Manifestation der einzelnen Persönlichkeiten fängt die Evolution des Bewusstseins der Persönlichkeiten an. Da die Involution und die Evolution des Bewusstseins von der Wahlfreiheit untrennbar sind, können sie auch nicht ohneeinander existieren. Die freie Wahl der Menschheit im Zustand der Involution führt zur freien Wahl der Persönlichkeiten im Zustand der Evolution. Der Wechsel zweier Zustände von Bewusstsein, zum Beispiel Involution und Evolution, ist ein Rhythmus oder ein Zyklus von Bewusstsein.

Die Rhythmen

In einem beliebigen Rhythmus oder Zyklus existieren immer zwei sich abwechselnde Zustände als Folge des Prinzips der Zweiheit. Diese zwei Zustände kann man als zwei Gegenteile betrachten. Da es nichts ohne Bewusstsein gibt, kann man einen Rhythmus immer als einen Wechsel zwischen zwei Bewusstseinszuständen definieren. Solche Ereignisse wie Tag und Nacht, Einatmen und Ausatmen, Yin und Yang usw. sind auch die Rhythmen des Bewusstseins.

Die esoterische Philosophie aller Zeiten beschreibt das Leben des Weltgebäudes als ein rhythmisches Leben. Die indische Philosophie beispielsweise spricht vom Einatmen und Ausatmen Eines. Eines erlebt verschiedene Zustände seines göttlichen Lebens. Diese Zustände vergleicht man mit dem Einatmen und Ausatmen. Das Ausatmen Eines entspricht der Manifestation des Weltgebäudes aus dem Tao, das Einatmen entspricht der Auflösung des Weltgebäudes im Tao. So wechseln sich die Zustände des manifesten und nicht manifesten Weltgebäudes, die Zustände der Tätigkeit und der Ruhe, ab. Manvantara ist der Zustand der Aktivität und Pralaya der Zustand des in sich selbst ruhenden Eines.

Der Grund- oder Hauptrhythmus des Weltgebäudes ist von zwei Bewusstseinszuständen bestimmt. Vom Bewusstseinszustand, in dem Tao sich der Persönlichkeiten als die Wesenheiten mit Wahlfreiheit in sich bewusst ist, und vom Bewusstseinszustand, in dem alle Persönlichkeiten sich selbst als Tao bewusst werden. Dies entspricht der Manifestation des Weltgebäudes aus dem Tao und der Auflösung des Weltgebäudes im Tao. Es ist wiederum notwendig zu betonen, dass die Manifestation eines beliebigen Rhythmus eine Folge der freien Wahl ist. Der Hauptrhythmus ist eine Folge der freien Wahl des Tao, sich der endlichen Anzahl der Persönlichkeiten in sich bewusst zu sein, als auch eine Folge der freien Wahl aller Persönlichkeiten sich selbst als Tao bewusst zu werden.

Die numerische Charakteristik dieses Rhythmus ist die endliche Anzahl der Persönlichkeiten im manifesten Weltgebäude. Da die Manifestation der endlichen Anzahl der einzelnen Persönlichkeiten nur nach dem Involutionsabschluss des Menschheitsbewusstseins geschieht, müssen alle Rhythmen, die im Weltgebäude manifestieren sein können, der Menschheit im Zustand der Involution bewusst sein. Da im Weltgebäude die Persönlichkeiten mit Wahlfreiheit und die Hierarchien des Bewusstseins ohne Wahlfreiheit manifestiert sein müssen, müssen die Rhythmen durch die Hierarchien des Bewusstseins ohne Wahlfreiheit manifestiert werden. Im Involutionszustand wird die Menschheit sich der verschiedenen Rhythmen von Bewusstsein, Leben und Form bewusst, welche die einzelnen Persönlichkeiten während der Involution erleben müssen, um sich selbst als Tao bewusst zu werden.

Der Involutionszustand des Menschheitsbewusstseins ist zeitlos und raumlos. Raum und Zeit werden erst im Zustand der Evolution manifestiert. Die Evolution des Bewusstseins der Persönlichkeiten geschieht in Raum und Zeit. Involution und Evolution zusammen bilden die schöpferische Tätigkeit des manifesten Weltgebäudes. Entsprechend der indischen Philosophie muss der schöpferische Tätigkeitszyklus von der schöpferischen Untätigkeit abgelöst werden, in der das manifeste Weltgebäude im Tao aufgelöst ist. Dabei wird erwähnt, dass die Zustände der schöpferischen Tätigkeit (Manvantara) und der Untätigkeit (Pralaya) die gleiche Dauer haben.

Im Zustand der Involution erzeugen die Persönlichkeiten noch kein Karma, sondern die freie Wahl der Menschheit bereitet die Bedingungen für die freie Wahl der einzelnen Persönlichkeiten in der Evolution vor. Das Karma kann von den einzelnen Persönlichkeiten nur im Zustand der Evolution erzeugt werden. Deshalb kann man den Involutionszustand mit dem Zustand von Pralaya und den Evolutionszustand mit dem Zustand von Manvantara vergleichen.

Es ist notwendig, auf eine bestimmte Schwierigkeit hinzuweisen, die bereits beim Vergleich der Dauer Maha-Pralaya von Involution und Evolution entsteht. Die Involution geschieht vor der Manifestation von Zeit und Raum. Die Evolution geschieht in Zeit und Raum. Es ist nur möglich, in Einheiten von Zeit und Raum zu vergleichen. Solche Einheiten des Vergleichs sind Rhythmen, die erst im Zustand der Evolution manifestiert werden. Im Zustand der Involution sind die Rhythmen aber noch nicht manifestiert, weder Zeit noch Raum sind manifestiert, deshalb ist es unmöglich, die Dauer von Involution und Evolution zu vergleichen. Es ist dennoch möglich zu behaupten, dass alle Rhythmen, die der Menschheit im Involutionszustand bewusst sind, auch den einzelnen Persönlichkeiten im Zustand der Evolution bewusst sein werden. Und in diesem Sinn kann man behaupten, dass Involution und Evolution die gleiche Dauer haben.

Die noch größere Schwierigkeit entsteht beim Versuch, die Dauer des Zustandes des manifesten Weltgebäudes und die Dauer des Zustandes, in dem das Weltgebäude im Tao aufgelöst ist, zu vergleichen. Einen solchen Zustand nennt man in der indischen Philosophie Maha-Pralaya. Ist es möglich, den Zustand der unendlichen Einsamkeit und Einigkeit des Tao in Rhythmen des manifesten Weltgebäudes, dessen Quelle Tao ist, zu vergleichen? Die indische Philosophie verweist beispielsweise auf die Dauer unseres Weltgebäudes in Erdjahren und setzt ihre Zahl der Dauer des Maha-Pralaya gleich.

Ähnliche Berechnungen lassen sich auch in anderen Quellen finden. H. P. Blavatskaya gibt im zweiten Band der Geheimlehre den Wert von 311040 × 10⁹ Erdjahren an. Auch wenn sich die verschiedenen Berechnungen voneinander unterscheiden mögen, bleibt ihr Sinn derselbe. Alle Berechnungen drücken die Dauer des Weltgebäudes in einer endlichen Anzahl von Erdjahren aus und setzen sie gleich der Dauer des Maha-Pralaya-Zustandes, in dem kein Weltgebäude manifestiert ist und Tao in seiner unendlichen Einsamkeit und Einigkeit verweilt.

Nimmt man an, dass Tao in seiner unendlichen Einsamkeit und Einigkeit genau soviele Erdjahre verweilt, wie das Weltgebäude dauern kann, würde dies bedeuten, dass Tao einem Rhythmus unterliegt. Tao ist aber die Quelle jedes beliebigen Rhythmus und kann keinem Rhythmus unterworfen sein. Kann Tao, der sich allen Möglichkeiten der Manifestation der Weltgebäude in sich immer bewusst ist, eines solchen Zustandes bedürfen, dessen Dauer mit der endlichen Zahl an Erdtagen bemessen sein kann, bevor das nächste Weltgebäude manifestiert wird? Wenn Tao sich aller Möglichkeiten der Manifestation des nächsten Weltgebäudes immer bewusst ist, kann der Zustand des Maha-Pralaya sofort in den Involutionszustand des nächsten Weltgebäudes übergehen. Selbst wenn eine gewisse Pause zwischen dem Ende des vorhergehenden und dem Anfang des nächsten Weltgebäudes existierte, wäre es unmöglich, sie in Einheiten des manifesten Weltgebäudes zu messen. Deshalb können derartige Berechnungen nur eine Charakteristik des manifesten Weltgebäudes sein. In diesem Sinn ist die Zahl der Erdjahre eine Charakteristik der Rhythmenanzahl, die jede Persönlichkeit erleben muss, um sich selbst als Tao bewusst zu werden.

Dennoch existieren zwischen den Zuständen, in denen das Weltgebäude manifestiert und nicht manifestiert ist, immer Beziehungen, auf die man verweisen kann. Einerseits sind dem Tao im nicht manifesten Weltgebäude alle möglichen Folgen der freien Wahl bekannt, aber die freie Wahl selbst kann von den einzelnen Persönlichkeiten noch nicht getroffen werden, da die Persönlichkeiten noch nicht manifestiert sind. Andererseits sind den Persönlichkeiten im manifesten Weltgebäude alle möglichen Folgen einer beliebigen freien Wahl unbekannt, aber die Wahl selbst kann getroffen werden. Diese beiden Seiten sind Ausdruck der Beziehungen, die man für manifeste und nicht manifeste Weltgebäude als gleich betrachten kann. Diese Beziehungen existieren immer, weil im unendlichen Bewusstsein des Tao immer die Möglichkeiten der Manifestation von neuen Weltgebäuden existieren.

Das Weltgebäude wird beendet, wenn jede Persönlichkeit sich selbst als Tao bewusst ist. Nur dann kann die endliche Anzahl der Persönlichkeiten im manifesten Weltgebäude jeder Persönlichkeit bekannt werden. Deshalb kann im manifesten Weltgebäude keine Wesenheit wissen, wie das nächste Weltgebäude sein wird. Es gibt keine Möglichkeit, vorhandene und nächste Weltgebäude zu vergleichen, weil nicht bekannt ist, was im nächsten Weltgebäude manifest sein kann. Es ist dennoch möglich zu sagen, dass sich das nächste manifeste Weltgebäude niemals wiederholen wird, da die Anzahl der Persönlichkeiten in jedem einzelnen Weltgebäude immer verschieden ist. Das nächste Weltgebäude kann nicht etwas beinhalten, was von Persönlichkeiten in den zahllosen vorhergehenden Weltgebäuden durch die freie Wahl bereits erkannt wurde. Sonst wäre dem Tao im Voraus bekannt, welche Wahl die Persönlichkeiten treffen werden, und eine solche Wahl wäre nicht frei. Das wahre Ich einer Persönlichkeit ist Tao. Deshalb war das Ich jedes beliebigen Menschen immer in den Persönlichkeiten in vorhergehenden Weltgebäuden manifestiert und wird in den Persönlichkeiten in der folgenden Weltgebäuden immer manifestiert sein. Das Wissen über das vorhergehende und nächste Weltgebäude befindet sich außerhalb des Bewusstseins der einzelnen Persönlichkeit im manifesten Weltgebäude.

Die freie Wahl der Menschheit im Involutionszustand führt zum weiteren Bewusstsein der Menschheit über die Prinzipien von Bewusstsein, Leben und Form. Der Zustand der Involution ist ein rein innerer Zustand, in dem äußerlich noch nichts manifestiert ist und in dem sich alles, was manifestiert sein wird, im Bewusstsein der Menschheit befindet. Weder die Prinzipien, noch die einzelnen Persönlichkeiten haben schon ein selbständiges Dasein. Die Prinzipien bekommen das selbständige Dasein zusammen mit der Manifestation der einzelnen Persönlichkeiten. Die Manifestation der einzelnen Persönlichkeiten bedeutet den Anfang der Evolution. Beim Übergang von Involution zu Evolution wird der niedrigste Zustand der Prinzipien von Bewusstsein, Leben und Form erreicht. Dieser niedrigste Zustand ist höher als jeder Zustand der sich entwickelnden einzelnen Persönlichkeiten und Prinzipien. 

'''
)

ru_invol = _('''                                                                                                                                                                                
Тао породило Один.
Одно породило Два.
Два породило Три.
А Три породило десять тысяч вещей. (Дао Дэ Цзин 道德經 42)

'''
)

invol = {"en":en_invol, "de":de_invol, "ru":ru_invol, }

st.title(_("Involution"))

st.write(invol[st.session_state.itaolang])




