
import streamlit as st
import gettext


localizator = gettext.translation('messages', localedir='locales', languages=[st.session_state.itaolang])
localizator.install() 
_ = localizator.gettext 

en_evol = _('''                                                                                                                                                                                
The ten thousand things carry yin and embrace yang. (Tao Te Ching 道德經 42)

To the end of involution mankind is conscious of all principles which can be manifested as separated beings in the state of evolution. This state could be called a pause. 

Such a pause does not mean inactivity, but only some intermediate state of consciousness of mankind between involution and evolution. It is necessary in order that all personalities could determine with which consciousness they will be manifested. Personalities have now such consciousness that allows them to be conscious of all possibilities of manifestation of principles of consciousness, life and form. This allows them also momentarily to become conscious of all possible consequences of free choice. Therefore, the first free choice in pause between involution and evolution all personalities can make together. If first free choice would not be made by all personalities together, then the choice of one personality could predetermine the choice of another personality what would contradict the freedom of choice.

The first free choice signifies beginning of evolution and is choice to manifest personalities, as single separated beings. In involution consciousness and will of all personalities were still manifested as uniform consciousness and will of whole mankind. In evolution consciousness and will of mankind are manifested in personalities and in different principles through the hierarchies of consciousness without freedom of choice. Personalities can make now their free choice, according to their consciousness and will. Single principles are manifested as beings, whose consciousness is expressed in different rhythms or cycles. Therefore, evolution in the world structure can be described proceeding from rhythms of oneness, duality, trinity and so on. 

Three kingdoms of consciousness

Separated personalities were manifested on different stages of the hierarchies of consciousness. The stages of consciousness of the hierarchies differ from each other by the stages of conscious following to rhythms of the development of consciousness of the world structure. One of such rhythms is rhythm of trinity or Holy Trinity. According to this rhythm three are manifested three kingdoms of consciousness. 
    
The first free choice of all personalities manifested three kingdoms and determined in which kingdom and with which consciousness every personality is manifested. Because personalities are manifested with different consciousness, there must be manifested personality with the highest consciousness in each kingdom. The names of these personalities are known as kings: Michael, Lucifer and Uriel. 

Lucifer also is called devil what literally means the 'fallen God'. Being without freedom of choice cannot fall by itself because action scheme of such a being is always predetermined in advance. Only free choice of Lucifer could lead him to that, what is called the fall. Besides, the name Lucifer signifies the 'bearer of light' or the 'light-bearer'. In the beginning of evolution Lucifer had the highest consciousness among all personalities. The consequence of the fall of Lucifer is that he is not personality with the highest consciousness any more. The highest consciousness has Jesus Christ. This does not mean Lucifer has lost his consciousness or his high wisdom. This means Jesus Christ has developed his consciousness so far, that it became higher than consciousness of any personality in our world structure. 

All personalities together have made their free choice, which allowed Lucifer to have the highest consciousness among personalities. Some personalities manifested themselves on lower stage of consciousness and have allowed other personalities to manifest themselves on higher stage of consciousness and vice versa. All personalities have made their mutual sacrifice, because they have made their first free choice together. No personality was forced by another personality to its choice and all personalities remained equally free. Therefore, personalities on lower stage of consciousness can develop their consciousness even more quickly than personalities, which are manifested on higher stage of consciousness. In other words, the speed of the development of consciousness depends not so much on stage of consciousness on which personalities are manifested, but rather depends on which free choice will be made.
Because any personality is member of whole mankind, any free choice of personality always exercises influence over the development of consciousness of other personalities. The higher is stage of consciousness of personality, the more influence can be exercised and the more responsibility personality has in determination of its choice. Responsibility of personality is determined by Karma to which free choice of personality leads. Beside individual Karma, all personalities, without exception, create Karma of mankind.

Lucifer had possibility to allow personalities in his kingdom, to manifest only those relations with beings of the hierarchies, whose consequences he himself could foresee. According to his stage of consciousness Lucifer has chosen to remove restrictions on connection of personality with beings of the hierarchies. This allows personalities in kingdom of Lucifer to become dependent on connection with beings of the hierarchies and to manifest greatest evil. 

It is possible to give an example of manifestation of good and evil. If child is fed with spoon, when it cannot do this yet by itself, then it is good. If this is continued when child is already in a state to do it by itself, then it would be evil, because that will not correspond to the development of consciousness of child in rhythm of the development of consciousness of mankind. One and the same action with the same intention of good can manifest good in one state of consciousness, and in other state of consciousness be evil. The following saying points to connection between good and evil: "The road to hell is paved with good intentions".    

Speaking in general, if free choice of personality does not correspond to rhythm of the development of consciousness of mankind, then it is evil. Free choice of personality which leads to manifestation of evil means separation of consciousness of personality from consciousness of mankind, through connection with beings of the hierarchies of consciousness. It is expressed in that, that personality strives for satisfaction of egoism without taking into consideration other personalities. The more is separation, the more is evil which can be manifested by personality through its free choice. To balance result of the greatest separation of personalities, it is also necessary through free choice to manifest the greatest good that leads all personalities to consciousness of unity of mankind. In this sense, the greatest evil exists in order to manifest the greatest good.

Lucifer had possibility to restrict connection of personality with beings of the hierarchies of consciousness, not allowing personality to become dependent on beings. Just as Tao allows mankind to be free in its choice of the development of consciousness, Lucifer also allows personalities in his kingdom to be free in the development of consciousness through manifestation of good and evil. Tao, however, has infinite consciousness and knows all possible consequences of any free choice. In spite of fact, that consciousness of Lucifer was the highest, it is still finite, therefore, he could not foresee all possible consequences of his free choice. The free choice of Lucifer has led to that what one calls the fall.

The fall signifies that Lucifer could not counterbalance relations between personality and beings of the hierarchies in such a way, that personality could develop the ‘I’-consciousness keeping independence from beings of the hierarchies. The free choice of personality, which owing to decision of Lucifier manifests evil, creates Karma not only for personality, but also for Lucifer. Lucifer has become dependent on connections with beings of the hierarchies, which were manifested as result of free choice of other personalities. He became unfree and hence has fallen in a sense, that he could not counterbalance manifestation of evil, and in such a way to prevent influence of evil on himself.

In the kingdom of Lucifer there exists one personality which has used the choice of Lucifer in order to attain the highest consciousness of separation from mankind. This personality is called the devil, Mephistopheles, Ahriman. One should make distinction between the concepts of devil and Satan. Devil signifies 'fallen God' and is referred to Lucifer. Satan signifies those, who 'leads away from the God' or who 'separates from God'. In New Testament the words devil and Satan point accordingly to Lucifer and Ahriman.

The development of consciousness of personality in every kingdom has property which depends on consciousness of king. To understand better specific properties of the development of consciousness of personality in every kingdom, one can use the following analogy. The kingdoms of Michael, Lucifer and Uriel can be considered as three schools of the development of consciousness accordingly. In each school there are director, teachers and disciples. Director has the highest consciousness on which depends the education in school. In first school director gives teachers instructions what must be educated. Teachers carry out instructions of director without any objection, not because they have no personal opinion, but because consciousness of director is superior to consciousness of each teacher and he knows much more, than they do. In third school director consults with teachers, before they get instructions from him. This makes the main difference between first and third schools. Disciples, according to their level of consciousness, fulfil instructions of teachers. The development of consciousness of disciples in first and third schools occurs relatively slow. To accelerate the development of consciousness, director of second school makes decision to allow disciples to change conditions of education in his school. Conditions of education can be changed so far, that director becomes unable to conduct education. In this case someone else should take control over education.

Michael and Uriel made their choice which does not allow personality to manifest evil in their kingdoms. Personalities in kingdoms of Michael and Uriel have possibility to become conscious of evil through what corresponds to the concepts of contemplation, meditation or reasoning (thinking) in our kingdom of Lucifer. However one should not imagine that consciousness of modern man on the Earth is the same, as consciousness of personalities in kingdoms of Michael and Uriel. The lowest stage of consciousness of personality in their kingdoms is comparable with the stage of consciousness of Angel. Personalities on the stage of consciousness of Angel do not need to be manifested in physical body. Their free choice does not manifest such relations with the hierarchies of consciousness as physical birth, illness or death. They cannot impose sufferings on other personalities, but they can think about them and experience them through reflection. Because of that, the development of consciousness in kingdoms of Michael and Uriel occurs more slowly, than in kingdom of Lucifer. It is much faster to manifest good or evil through choice and to experience its consequences than to become conscious of all consequences of free choice through reflection. Confirmation for that is also Jesus Christ who was manifested in kingdom of Lucifer and has become personality whose consciousness is the highest in our world structure. Consciousness of Jesus Christ permeates through all three kingdoms, whilst consciousness of one king does not permeate through other kingdoms. 

Because Lucifer allowed personalities in his kingdom to manifest evil without restrictions, he has deprived himself of possibility to counterbalance evil. In order any personality always could have possibility to become conscious of itself as Tao, another personality must counterbalance evil with good in the kingdom of Lucifer. This personality is Jesus Christ. Thereby, nobody is deprived of freedom of choice to manifest evil. To manifest evil means also to manifest opposites by opposing consciousness of some beings to consciousness of other beings. Michael and Uriel have preserved their power to counterbalance relations between beings in their kingdoms. Lucifer also had such a power before his fall. 

The hierarchies of consciousness

Everything what man perceives through physical sense organs is only external expression of relations between the hierarchies of consciousness. The hierarchy of consciousness consists of beings of one kind which are comprised in consciousness of being which one calls Hierarch. Hierarch has highest consciousness in the hierarchy. Being with higher consciousness is able to become conscious of what a being with lower consciousness is able to become conscious of too. Therefore, Hierarch is always conscious of what single being of the hierarchy is conscious of. For example, any fire on the Earth is comprised in consciousness of Hierarch which the Indian tradition calls Agni. Agni is Hierarch of all beings of the element of Fire on the Earth.

Indivisibility is inherent in hierarchies of consciousness. For example, the hierarchy of Angels signifies all Angels that are united through consciousness of the Hierarch of Angels. The hierarchy is indivisible whole in a sense that single Angel cannot exist without other Angels of the hierarchy.

Man as only being with freedom of choice, forms his own hierarchy of consciousness, which is mankind. Unlike other hierarchies of consciousness, each member of mankind has freedom of choice and consequently has its own Hierarch. Hierarch of man is his individuality, his highest ‘I’ (Self) in the manifested world structure. Man cannot exist separated from his individuality, and individuality cannot exist separated from mankind. Consciousness of mankind is united consciousness of all human Hierarchs.

The teaching about the hierarchies of consciousness, as beings without freedom of choice, is a teaching about gods. There are known three  hierarchies of consciousness, named as follows. 

1st Hierarchy
1. Spirits of Love (Seraphims)
2. Spirits of Harmony (Cherubims)
3. Spirits of Will (Thrones)\n
2nd Hierarchy
1. Spirits of Wisdom (Dominions, Kyriotetes)
2. Spirits of Movement (Mights, Virtutes, Dynamis)
3. Spirits of Form (Powers, Potestates, Exusiai)\n
3rd Hierarchy
1. Spirits of Personality (Primal Beginnings, Beginnings, Archai)
2. Spirits of Fire, Messangers of Archai (Archangel, Archangeloi)
3. Sons of Life, Messangers (Angels, Angeloi)

Beings without freedom of choice can have consciousness higher and lower than consciousness of man. Those beings whose consciousness is higher than consciousness of man are called the heavenly beings or Devas. 

Similar to God can be only such being which has freedom of choice. Because the hierarchies of consciousness do not have freedom of choice, the similarity and union of hierarchy with God can occur only through free choice of personality. The consequence of the free choice of personality is the development of consciousness of personality, as well as of the hierarchies of consciousness. The higher is consciousness of personality the more it is conscious of possibilities of free choice. Because all possibilities of choice are manifested through the hierarchies of consciousness, the development of consciousness of personality occurs through inclusion of consciousness of beings of the hierarchies in consciousness of personality. If, for example, consciousness of personality encloses consciousness of Angel in itself, then it can become conscious of that, what Angel is conscious of. Consciousness of personality can be limited only by consciousness of the world structure. The end of the world structure can be reached only if consciousness of every personality is developed so far that it is conscious of all what can be conscious to all hierarchies. In such a way, personality with its consciousness can become superior to consciousness of any hierarchies or their combinations. 

The luciferic and ahrimanic beings

The idea of the development of the world structure is manifested through the hierarchies of consciousness which provide possibilities of free choice to personalities. In the beginning of evolution Michael, Lucifier and Uriel were the first among personalities who were conscious of the idea of the development of the world structure. Their free choice manifested new possibilities of choice for other personalities.

That man is conscious only of the physical world, results from his free choice. If free choice of man manifests evil, then this choice opposes consciousness of some beings of the hierarchies to consciousness of other beings, whose consciousness is lower, than consciousness of man. Possibility of such a choice has been manifested by Lucifier and Ahriman, therefore unfree beings, whose consciousness becomes opposed or set against to consciousness of other unfree beings, are called luciferic and ahrimanic beings. These beings also are called devilish and satanic beings. Man bears responsibility for opposition of consciousnesses of beings of the hierarchies against each other and, hence, for manifestation of devilish and satanic consciousness. Free choice of man corresponds to truth if it corresponds to consciousness of beings of the heavenly hierarchies, whose consciousness is higher, than consciousness of man. Such free choice heightens consciousness of man because consciousness of a heavenly being will be included in consciousness of man.

The presence of consciousness of devilish and satanic beings in consciousness of man is expressed in changes of consciousness which are called suffering, illness, old age, birth and death. If man were able to counterbalance connection with these beings according to consciousness of heavenly beings, then instead of birth and death he would experience a metamorphosis of one state of consciousness into another. Because man cannot do it by himself, then in order not to become completely dependent from devilish and satanic beings, his consciousness is limited by perception of physical world only.

The free choice of man always manifests certain relations between the hierarchies of consciousness and man. There occurs an exchange of consciousness. As result, single beings will be manifested which can influence next free choice of man. Beings themselves have no freedom of choice, therefore their consciousness is true. Lie is negation of reality. Therefore, if man lies he manifests beings whose consciousness truly reflects lie of man. They influence consciousness of other men so that lie which is truly reflected by consciousness of beings, will be perceived as truth, that is as influence of consciousness of heavenly beings. The strength of such influence depends on how much manifested beings can use consciousness of man. The more man lies, the stronger becomes influence of beings and the stronger will be dependence of man from beings. Similar occurs, when man is mistaken, that is when it unintentionally lies to himself. The main difference between mistake and lie is that consequences of mistake are less destructive for consciousness of man, than consequences of lie. 

Typical example of dependence from beings is desire to experience pleasure just for the sake of pleasure. In this case, an influence of manifested beings works as temptation. Temptation consists of that, that beings truly reflect that pleasure, which man can experience due to connection with beings. Man can give in to temptation and become dependent from beings of the hierarchies in determination of his free choice and in this sense to become unfree.     

Each time when man gives in to temptation, in consciousness of manifested beings will be included a part of consciousness of man. The use of consciousness of man by beings is the reason why man is predisposed to become feeble-minded, physically underdeveloped and ill since his birth. Dependence from beings may be so strong, that it is necessary to pass through several incarnations before man can be freed. The purpose of incarnation of man in physical body is the development of consciousness. In order man could be incarnated in some form of physical body, this form must be manifested as relations between the hierarchies of consciousness. For this purpose various beings pass through various incarnations also. The Earth also has passed through various incarnations before man could have the present form of physical body.

Consciousness, life, form

The incarnations of man are connected with incarnations of the Earth which occur corresponding to rhythms of the development of consciousness of mankind. According to the rhythm of trinity there are three members in any manifested being, which are called consciousness, life and form. With the names consciousness, life and form it is always necessary to understand relations between the hierarchies of consciousness manifested through free choice of personalities. In this sense evolution of consciousness of mankind is unfolding of consciousness of personalities in infinite consciousness of Tao through principles of consciousness, life and form.

What mankind has become conscious of in the state of involution is manifested in the state of evolution, on the one hand, as the universal rhythms of the world structure, of the Macrocosm, and on the other hand as personal rhythms of Microcosm. The rhythm of trinity is the rhythm of the world structure and is manifested in any being as consciousness, life and form. With the form it is necessary to understand that, what allows a being to have finite consciousness, and thus separates life of one being from another. The principles of consciousness, life and form correspond to spirit, soul and body in man. Anther rhythm of the world structure is septenary rhythm which is manifested in the development of consciousness, life and form. How much consciousness, life and form of man correspond to the universal rhythm, depends on his free choice. The interaction of free choice of personalities and rhythms of trinity, sevenness and so on, creates variety of manifestations of consciousness, life and form. Every man in present rhythm of the development of consciousness of mankind is personality who has the ‘I’-consciousness, or is conscious of itself as the ‘I’. Not all personalities had such consciousness in the beginning of evolution and in this sense they could become man only in subsequent rhythms of the development of consciousness. 

In order for man to have consciousness of himself as the ‘I’, his spirit, soul and body must be in certain relations to each other, that allow man to become conscious of his separation from his external environment. These relations between the hierarchies of consciousness were manifested through free choice of personalities which had the ‘I’-consciousness earlier, than man on the Earth. At what level of the hierarchies of consciousness each personality was manifested, it was determined by the first free choice of all personalities. Personalities which in the beginning of the evolution were manifested on the level of second hierarchy and higher, from the very beginning of the evolution had the ‘I’-consciousness. Other personalities did not have such ‘I’-consciousness yet and must pass through certain stages of the development of consciousness. 

It is hardly possible to find out more detailed description of the stages of the development of consciousness corresponding to consciousness of modern man, than in books and lectures of Rudolf Steiner, which were written in the beginning of XX century. Because consciousness of mankind has changed since then, there is possibility to point out to the freedom of choice directly. Everywhere in works of Rudolf Steiner where it is possible to find the words about beings of the hierarchies staying behind, about sacrifice of beings of the hierarchies, it is always a talk about personalities staying on certain level of the hierarchies of consciousness, because to make sacrifices or to stay behind in the development of consciousness it is possible only then when one has the freedom of choice.

The Saturn state of consciousness

The first words in the Gospel of St. John "In the beginning was the Word" mean that "In the beginning was the freedom of choice", and specify that state of evolution when personalities on the level of consciousness of the hierarchy of the Beginnings developed their ‘I’-consciousness through free choice. This state of evolution in the kingdom of Lucifier is called the Saturn state of consciousness. It corresponds to the rhythm of all-mightness (omnipotence) which became conscious to mankind in the state of involution. This rhythm was manifested in each of three kingdoms differently. The manifestation of the rhythm of all-mightness in the kingdom of Lucifier is the Saturn state of consciousness.

In the Saturn state of consciousness Lucifier makes his free choice to remove limitations to manifest good and evil in his kingdom. In order to have the ‘I’-consciousness, it is necessary to become conscious of separation from all what is manifested. Therein there is also a possibility of manifestation of greatest evil. The greatest evil can be manifested through personality, which in consequence of its free choice will attain the highest consciousness of separation from mankind. In the Saturn state personality which is called Satan, Mephistopheles and Ahriman has used such possibility. Ahriman has manifested his ‘I’-consciousness as the highest principle of separation, possibility of which was provided by the free choice of Lucifier. Therefore it is said that Ahriman is Karma of Lucifier. In the Saturn state the principle of separation developed by Ahriman corresponded to the rhythm of all-mightness, that is why it was timely suitable and necessary for the development of the ‘I’-consciousness of personalities through free choice.

Because consciousness of Lucifier was the highest one, to know about his free choice it is only possible because he has made it accessible for supersensible perception. The same relates to the free choice of Ahriman to manifest the highest consciousness of separation. And the more it will be true for free choice of Christ. Lucifier, Christ and Ahriman make their free choice with objective of development of consciousness of other personalities. Their free choice is a sacrifice and they do not have intension to get any benefit from it or to hide it. The more it will be known about their free choice and those possibilities of manifestation which follow from it, the more other personalities can make their free choice consciously.

In the Saturn state of consciousness man had the lowest dull trance-consciousness, which comparable with consciousness of a stone or a mineral on the Earth. A being with trance-consciousness on the Earth is not conscious of itself as a being separated from its environment at all, but is conscious of itself only as a part of its environment. It perceives movements of planets, mineral forms, forms of crystals and so on, but plants, animals and man cannot be perceived by such a being. It is possible for it to perceive forms in the world structure, but not life of forms. Because personalities with trance-consciousness did not separate themselves from their environment yet, their free choice always corresponded to rhythm of the development of consciousness of mankind. Because the form of manifestation of a being depends on its level of consciousness, man in the Saturn state also had form and life other than modern man on the Earth.

In the Saturn state of consciousness man has such manifested physical body the development of which was influenced by free choice of personalities of the level of consciousness of Archai. Physical body of man had at that time quite different form, than it is now. All physical bodies of men were manifested as one physical body of the whole Saturn state of consciousness. The relations between the hierarchies of consciousness manifested as substance of physical body in the Saturn state of consciousness are called Warmth, or Fire. Manifestation of Warmth was connected mainly with free choice of personalities of the level of consciousness of Spirits of Will. Physical body of man that consisted of Warmth was changed under the influence of free choice of personalities of the level of consciousness of Archai.

The Sun state of consciousness

The rhythm of all-mightness was followed by the rhythm of all-wisdom which in the kingdom of Lucifier was manifested as the Sun state of consciousness. Not all personalities on the level of consciousness of Archai were able to develop the proper ‘I’-consciousness before the Sun state of consciousness has come to an end. Such personalities have stayed behind rhythm of the development of consciousness of mankind in the development of their ‘I’-consciousness. The staying behind was not forced, but it was consequence of free choice of personalities. The rhythm of all-mightness continued to act in the Sun state of consciousness also, but it was not predominated any more. All previous rhythms always continue to act in following rhythms, but relations between them change due to free choice of personalities. Therefore, personalities which were not able to develop proper ‘I’-consciousness in previous rhythm, have possibility to continue the development in next rhythm, if it was allowed by new relations. In the Sun state of consciousness the ‘I’-consciousness developed personalities which were on the level of consciousness of the hierarchy of Archangel.

Personality which is known now as Jesus Christ was manifested on the level of consciousness of the hierarchy of Powers, or Spirits of Form in the Saturn state of consciousness. In the Sun state of consciousness Jesus Christ attains the highest ‘I’-consciousness among personalities with the level of consciousness of the hierarchy of Powers. The principle of separation developed by Ahriman is manifested in the Sun state of consciousness as the principle that prevents the development of the ‘I’-consciousness of Jesus Christ.  Consciousness of Ahriman was still higher than consciousness of Jesus Christ and it influenced all personalities. The consequence of such influence of Ahriman was that in the Sun state of consciousness one personality which is called Sorat, or the Sun-demon has developed such consciousness which was opposed to consciousness of Jesus Christ.
    
In the Sun state of consciousness man had already dreamless sleep consciousness, which is comparable with consciousness of single plant on the Earth. A being with this consciousness on the Earth perceives life in minerals and plants, but the animal kingdom, feelings and thoughts do not exist for such consciousness. This state of consciousness is already less dull, but it is also less comprehensive, than the trance-consciousness. Free choice of man with dreamless sleep consciousness also corresponded to rhythm of the development of consciousness of mankind in the Sun state of consciousness.

In the Sun state of consciousness to the relations between the hierarchies of consciousness manifested as physical body of man, were added other relations which were manifested as the etheric body. The addition of substance of the etheric body has been connected mainly with free choice of personalities of the level of consciousness of Spirits of Wisdom. The etheric body supported more stable form of the physical body, than it was in the Saturn state of consciousness. The alterations of the etheric body of man were influenced by free choice of personalities of the level of consciousness of Archangel. The physical body of man becomes manifestation of the relations between the hierarchies of consciousness which are called Air. Such relations made physical body still more stable to the alterations, taking place in the etheric body, owing to free choice of Archangels.

The Moon state of consciousness

The next rhythm all-love was manifested in the kingdom of Lucifier as the Moon state of consciousness. In this state the ‘I’-consciousness developed personalities which were on the level of consciousness of the hierarchy of Angels. Among Spirits of Form in the Moon state of consciousness the highest ‘I’-consciousness was attained by personality which is called Jehova, or Jahve. Jehova already has been manifested on the level of consciousness of the hierarchy of Powers, or Spirits of Form in the Saturn state of consciousness. However the leading personality among Spirits of Form Jehova becomes only in the Moon state of consciousness.

In the Moon state of consciousness for the first time was manifested that, what it is called the fight in heaven or the war in heaven. The war is always connected with violation of freedom of choice of personality. If one man wishes something that will contradict freedom of choice of other man this will wage war with other man. Though this war may not be manifested on physical level, however it is manifested on level of consciousness which is called mental and on which thoughts are real beings. Similarly, if man experiences feeling of hate or anger in relation to other man, then such war is manifested on level which is called astral where feelings, emotions, passions and lusts are real beings. For example, behind manufacture of arms there are always thoughts to kill. Therefore when men produce weapons they already wage war with other mankind on the mental level. If the feelings of benefit, greed, pride, envy, anger and similar are added to such thoughts, a war is waged not only on the mental, but also on the astral level of consciousness and it is not far away to its manifestation on the physical level at all.

The first war was waged on the level of consciousness of Angels which is higher than the level of waking consciousness of modern man on the Earth therefore this war is called the war in heaven. Personalities on the level of consciousness of Archangels, Archai and higher made their free choice which could lead to mistakes, but it corresponded to rhythm of the development of consciousness of mankind. Therefore personalities on the level of consciousness higher than of Angels did not manifest evil. Their consciousness was high enough to make free choice, not violating the freedom of choice of other personalities. Personalities on the level of consciousness of Angels in the Moon state of consciousness for the first time began to make free choice depending on personal sympathies and antipathies which could contradict the freedom of choice of other personalities.

The free choice of Lucifier caused that some personalities could stay behind in their development because of free choice of other personalities. The free choice of personality is always manifested through beings of the hierarchies without freedom of choice. Therefore all hierarchies of consciousness have been involved in the war in heaven. Since then there were many wars and they will proceed to exist until it will be realized, that free choice of one personality must not violate free choice of other personalities.

In the Moon state of consciousness man had dreaming sleep consciousness, which is comparable with consciousness of single animal on the Earth. Such consciousness, besides the forms of mineral, plant and animal kingdoms, also perceives life and feelings of beings of these kingdoms. Such consciousness is still less comprehensive, than previous one, however free choice of personality with this consciousness still corresponded to rhythm of the development of consciousness of mankind.

To the physical and etheric body of man in the Moon state of consciousness were added relations between the hierarchies consciousness called astral body. The addition of substance of the astral body has been connected mainly with free choice of personalities of the level of consciousness of Spirits of Movement. Now free choice of personalities of  the  level of consciousness of Angels influenced the development of the astral body of man. The free choice of personalities of the level of Angels could, however, manifest evil already. Therefore personalities with consciousness higher than consciousness of Angels acquired wisdom to make free choice so, that on the one hand, do not violate free choice of personalities with consciousness of Angels, and on the other hand, to the greatest degree to protect physical, etheric and astral body of man from an influence of evil. Eventually man has received protection against evil in physical and etheric body because they gave in to the influences of the astral body less of all. The physical body of man in the Moon state of consciousness has been manifested as relations between the hierarchies of consciousness which are called Water. Because in the Moon state of consciousness personalities acquired wisdom to make free choice without violation of free choice of other personalities, the Moon state of consciousness is called the Cosmos of Wisdom.

The Earth state of consciousness

The rhythm of all-justice was manifested in the kingdom of Lucifier as the state of consciousness of mankind called Earth. Here the ‘I’-consciousness develop those personalities, which, actually, are called man and which still had no such possibility in the states of Saturn, Sun and Moon and. What is called the Earth planet is a plenty of relations between hierarchies of consciousness which allow man to develop his ‘I’-consciousness. The Earth planet is a characteristic of the whole Earth state of consciousness in a sense that on the Earth planet personalities can have the lowest and the highest ‘I’-consciousness in the world structure. The highest ‘I’-consciousness could be attained by Jesus Christ on the Earth planet.

When the Earth state of consciousness has come to existence, wisdom as result of free choice of personalities in the Moon state, was manifested in such relations between physical, etheric and astral bodies of man which allowed him to develop the ‘I’-consciousness through his free choice. Such possibility of manifestation has been provided by free choice of personalities of the level of consciousness of the Spirits of Form. Up to the Earth state of consciousness man had no waking self-consciousness of himself as of personality. Now the ‘I’-consciousness could be manifested in physical body of man. The relations between the hierarchies of consciousness manifested as physical body of man are called the Earth. In wonderful construction of physical body of man it is possible to see manifestation of wisdom which has been attained by personalities in the Moon state of consciousness.  

Consciousness of single stone, plant and animal on the Earth could be manifested only because man had trance-consciousness, dreamless sleep consciousness and dreaming consciousness in Saturn, Sun and Moon states of consciousness. Therefore it would be mistake to imagine, that consciousness of single stone, plant, animal are exactly the same as there was consciousness of man. They were manifested due to free choice of man. Man, having these three kinds of consciousness, still had not separated himself from whole mankind and his free choice has always been agreed with free choice of other personalities. Only in the Earth state of consciousness man can make free choice which does not correspond to rhythm of the development of consciousness of mankind. Man begins to use his free choice for the manifestation of good and evil.    

Each of these states of consciousness in the kingdom of Lucifier is Manvantara when personalities create their Karma through free choice. The transition from one state of consciousness to another state of consciousness is carried out by personalities in state of Pralaya. In Pralaya personalities can experience the experiences of each other. For example, when personality lies, then the consequences of lie work destructive for consciousness of personality. In order to learn not to lie, it is not necessary for each personality to experience the consequences of its own lie it is enough to experience the experiences of other personality. Such possibility is provided in Pralaya to all personalities. Personalities do not create Karma in Pralaya, but process the results of free choice made in previous Manvantara and prepare to use them for the development of consciousness in following Manvantara.

The Earth state of consciousness icomprises the previous states of consciousness Saturn, Sun and Moon in itself. In this sense the previous states of consciousness were incarnations of the Earth being and had the mission to give man possibility to use forces of willing, feeling and thinking consciously.

According to four states of consciousness Saturn, Sun, Moon and Earth it is to distinguish four members or limbs in man: physical body, etheric body, astral body and the ‘I’. The development of the ‘I’-consciousness of man through mastering of willing, feeling and thinking corresponds to rhythm of the development of consciousness of mankind in the Earth state of consciousness. To bring these three elements through man consciously into balance makes up the mission of the Earth.

The seven kinds of consciousness of man

According to seven rhythms of the world structure, which mankind became conscious of in the state of involution, it is to distinguish seven states of consciousness in the kingdom of Lucifier. Seven kinds of consciousness, which man can have, correspond to seven states of consciousness in the world structure. To the four already described states Saturn, Sun, Moon and Earth will be added three more future states of consciousness Jupiter, Venus and Vulcan. All states of consciousness always exist together, beside each other and in each other, and became conscious to mankind as principles, in the state of involution. The involution and evolution of these principles is reflected in constitution of man. According to the seven states of consciousness there are seven members, limbs, or carriers of consciousness of man.

Trance-consciousness (Saturn, Physical body)
Dreamless consciousness (Sun, Etheric, life body)
Dreaming consciousness (Moon, Astral body)
Waking, day-consciousness (Earth, ‘I’ (Self))
Picture, imaginative consciousness (Jupiter, Self-Spirit, Manas)
Tone, inspirative consciousness (Venus, Life-Spirit, Buddhi)
Spiritual, intuitive consciousness (Vulcan, Spirit-Man, Atman)

Man is not limited only by these seven members. He is finite image of Tao, and enumeration of his seven members corresponds to septenary rhythm of the development of consciousness. There are other rhythms also, for example, nonary rhythm. According to nonary rhythm man consists of: physical body, etheric body, astral body, the ‘I’ , sentient soul, rational or feeling (psychic) soul, consciousness soul, spirit-self or Manas, life-spirit or Budhi, spirit-man or Atma.

The being of man is also described as consisting of four members or limbs: physical body, etheric body, astral body and the ‘I’. The fourth member - the ‘I’ (Self) - is the most complex member of all. It is individuality of man which contains all possibilities of development of the ‘I’-consciousness of personality. In modern man the ‘I’-consciousness comprise the sentient, rational and consciousness soul. It is expressed by that, that man can use feeling, thinking and willing consciously. The higher three members - Self-Spirit, Life-Spirit and Spirit-Man - will be developed in man when his astral, etheric and physical bodies will be completely under his conscious control. The rhythms for the development of higher members of man - Self-Spirit, Life-Spirit and Spirit-Man - will be manifested in future states of consciousness - Jupiter, Venus and Vulcan. This does not mean, man has no possibility to develop the higher members in the Earth state of consciousness. It means the development of the Earth has an objective of development of the ‘I’-consciousness of man through thinking, feeling and willing. When man will be capable to control consciously the processes of the astral body he will attain the development of Manas, or Self-Spirit. The consciousness in the etheruc body will signify the development of Buddhi, or Life-Spirit. Man becomes Atman, or Spirit-Man when the processes of physical body will be part of his waking ‘I’-consciousness. Man has these higher members in himself already, but he still cannot control them consciously. 

The description of members of man is only a sketchy description out of which one should not make dogmas. Human being is much more complex, than it could be described at all. All hierarchies of consciousness participate in manifestation of human being and in order to describe it completely, it would be necessary to describe all possible relations between the hierarchies of consciousness. Therefore it is always possible to extend any description. For example, the astral aura of man in physical body has form of an oval, or an egg because the etheric, or life (vital) currents which permeate the astral body, form so-called etheric, or energetic cocoon which has shape of an oval, or an egg in man. It is necessary to understand the etheric, vital or energetic currents as relations between the hierarchies of consciousness which for the supersensible perception appear as streams or currents. All sentient living beings on the Earth have etheric cocoon which is connected with etheric body of the Earth. Death of being in physical body comes when its etheric cocoon will be destroyed. The etheric cocoon of man appears at the moment of physical conception and it keeps connection of the etheric body with physical body of man. When the etheric cocoon is destroyed, the etheric body is released from physical body and there comes alteration of consciousness called death. After death man can preserve his waking consciousness in the astral body if he has appropriate qualities, or attributes. The astral aura of man is a colour characteristic of qualities of man, laid on the etheric cocoon. 

Life after death

During life in physical body man is not conscious of, that he is not only in physical, but also in the soul and spiritual world, among beings of the hierarchies of consciousness. In occultism the soul world is called astral world, and the spiritual world - devachanic world, or Devachan.

The expressions sky, heavens, heavenly world are used for a designation of the world of the heavenly hierarchies, whose consciousness is higher than consciousness of man. Because the hierarchies of consciousness are manifested together, beside each other and in each other, all worlds are manifested together too. Man is manifested in all worlds, but in waking consciousness in physical body he is conscious only of the world of physical space and time.

Perception of space is connected with perception of manifestation of the hierarchies of consciousness beside each other, and perception of time - with perception of rhythmic sequence of alteration of relations between the hierarchies of consciousness. In this sense space and time exist until exists the manifested world structure and their perception depends on the level of consciousness of personality. Man in physical body is conscious of space of three dimensions, and of time - as a sequence of alterations in space. The soul and spiritual worlds are not physically spatial and timely worlds, therefore man in physical body is not conscious of them. His waking consciousness does penetrate through threshold of supersensible space and time. When man falls asleep, he crosses this threshold and loses that content of the waking consciousness which is adapted only for physical space and time. It can make clear why man, waking up, cannot recollect, what he perceives behind threshold of the supersensible world. Man crosses this threshold completely when his consciousness changes through death. The fear of death is connected with unconscious fear of sufferings which have to do with the loss of content of consciousness of physical space and time.

To adapt himself to the soul and spiritual worlds after death, man first must free himself from the connections with beings of the hierarchies which he has established, striving to satisfy lusts and desires through physical body. The state of consciousness in which man is purified from sensual lusts and desires of the physical world is called the purgatory, Kamaloka – the 'place of desires' in Sanskrit. The deprivation of a possibility to get satisfaction of desire through physical body causes sufferings. The more consciousness of man, deprived of physical body, is connected with pleasures of the physical world, the more is suffering of purification. Kamaloka is not physical place, it is state of consciousness, Man is protected from direct perception of Kamaloka by physical body. To perceive the state of Kamaloka, it is not necessary to pass through death, it is sufficient to develop supersensible organs of perception during life in physical body.

Kamaloka is situated in the astral world, where lusts and desires of man are manifested through beings, which are called Kama-devas. In a similar way to how physical body of man has materiality, corporeality of devas also has some materiality. Materiality needs to be understood as such level of consciousness on which consciousness, life and form of beings of the hierarchies are manifested in equal proportions. The body of Kama-devas possesses astral materiality. The devachanic world, Devachan, is subdivided into low and higher areas. The low Devachan is the mental world where thoughts of man are manifested through beings called Rupa-devas. The higher Devachan is the world of intentions, ideas and plans. Here there are all possibilities of manifestation of relations between the hierarchies of consciousness through the free choice of personality. The beings of the higher Devachan are called Arupa-devas. According to the higher and low Devachan it is to distinguish in man the causal and mental body.

The causal body of man has originated in the beginning of evolution together with the first free choice of all personalities. Every personality has causal body which contains any choice that has already been made by personality. The made free choice is impossible to change, it is only possible to make next free choice. The made free choice is preserved unchanged from incarnation to incarnation and in this sense the causal body it is impossible to change too.     

For example, to Kama-devas belong beings which in the Middle Ages have been still perceived as gnomes, undines, sylphs, salamanders. To Rupa-devas belong beings of third, and to Arupa-devas belong beings of first and second hierarchies of consciousness. In the spiritual world there is a level of consciousness which is called Akasha-chronicle. All results of free choice of personalities could be perceived on this level of consciousness. When one investigates Akasha-chronicle supersensibly, then it is possible to make conclusions about the free choice of personality only from the results of free choice. The free choice itself, as a cause, is imprinted in causal body of personality and cannot be investigated by others. The free choice is made through Tao and is an intimate act between personality and Tao. It can become known to others through Akasha-chronicle only with the consent of personality itself.

Everything is manifested through the hierarchies of consciousness, therefore everything, what man perceives through his physical organs of perception, exist in other spaces as relations between the hierarchies of consciousness. After death instead of planets of the Solar system man perceives the hierarchies of consciousness and boundaries of their ruling realm. Man becomes conscious of himself in other spaces, when he is conscious of the hierarchies of consciousness. The space of Kamaloka, which is in the area of the Moon, will correspond to realm of the hierarchy of Angels. After state of Kamaloka man extends his life up to life of other planets of the Solar system. This corresponds to life in the realms of still higher hierarchies of consciousness. In the astral world in centre of activity of the hierarchies of consciousness is the Earth. The Sun is boundary of ruling realm of the Spirits of Form and is one of planets of the Solar system. In occultism the planet nearest to the Sun is called Venus, and the second from the Sun - Mercury. In natural science the names of the planets Mercury and Venus are interchanged. In the following table are present the planets of the Solar system and the corresponding boundaries of ruling realms of the hierarchies of consciousness.

Moon (Angels)
Mercury (Archangels)
Venus (Spirits of Personality, Archai)
Sun (Spirits of Form, Powers)
Mars (Spirits of Motion, Mights)
Jupiter (Spirits of Wisdom, Dominions)
Saturn (Spirits of Will, Thrones)

Modern man has his waking consciousness in physical body because owing to physical body he can become conscious of his own differentiation from his surroundings and to have the ‘I’-consciousness. After death of his physical body he loses part of waking consciousness already during purification in Kamaloka. On the one hand, he loses possibility to become conscious of himself because of lack of physical body, and in this sense his consciousness becomes more dull, and on the other hand, this allows him to extend his perception in the realm of Angels. To preserve his waking consciousness in the realm of Angels and in higher realms of the hierarchies of consciousness, man must possess properties, inherent to consciousness of beings of these realms. In a sense of exchange of consciousness these properties can be characterized by two words – taking and giving. Beings of the hierarchies of consciousness without freedom of choice do not choose, how much to take and give. They can take and give only as much, as it is prescribed to them by rhythm of the development of consciousness of mankind. As man has freedom of choice, these properties correspond to the qualities of renouncement and sacrifice. Both these qualities together is a characteristic of quality of love and of freedom from egoism. To preserve his waking consciousness, man must by himself counterbalance exchange of consciousness with beings of the hierarchies, making free choice how much to take and to give in a sense of setting connections with the hierarchies of consciousness. He must be able to refuse to take more, than it is necessary for the development of his consciousness and to be able to sacrifice his free choice for the sake of development of consciousness of other beings according to rhythm of the development of consciousness of mankind. And the higher are his qualities of renouncement and sacrifice, the longer he can preserve his waking consciousness after death. Independent of these qualities, his life and perception extend up to life of the hierarchies of consciousness.

Further extension of life of man after death leads him in the realms of Thrones, Seraphims and Cherubims. The human life extends up to the life of the Cosmos. Physically this corresponds to the area of twelve constellations surrounding seven planets of our Solar system. These constellations form so-called animal circle, or zodiacal circle - Zodiac. The names of signs of animal circle refer to connection of the hierarchies of consciousness with manifestation of human form and form of animals.
    
The physical form of man allows him to have the ‘I’-consciousness on the Earth. All hierarchies of consciousness which are manifested in it are manifested in configurations of stars, planets, animals, plants and minerals too. Physical form of modern man is only one of all possible forms in which man can have the ‘I’-consciousness. All possibilities of manifestation of such forms are in his individuality. In antiquity the connection of individuality with the form of manifestation of man on the Earth was designated in form of cosmic man inscribed in the animal circle - Zodiac. Each part of human form was drawn to the corresponding constellation of animal circle from which acted Thrones, Cherubims and Seraphims. Thus, one has giant cosmic man from whom every single man has got his physical form.

1. Head (♈Aries, Ram)
2. Neck (♉Taurus, Bull)
3. Arms (♊Gemini, Twins)
4. Breast (♋Cancer, Crab)
5. Heart (♌Leo, Lion)
6. Stomach (♍Virgo, Maiden)
7. Pelvic gridle (♎Libra, Scales)
8. Genitals (♏Scorpio, Scorpion, Eagle)
9. Thighs (♐Sagiitarius, Archer)
10. Knees (♈Capricon, Sea-Goat)
11. Low legs (♒Aquarius, Water-Bearer, Man)
12. Feet (♓Pisces, Fish)

Which form of manifestation modern man has, depends on his level of consciousness, and in the future, with the alteration of his consciousness, the form of his manifestation will change as well. In order man could have the form of physical body and to be conscious of physical space and time, interaction of all hierarchies of consciousness is necessary. The highest level of consciousness among the hierarchies, have Seraphims, Cherubims and Thrones. Above their consciousness there is level of consciousness of Trinity which is designated as the One, Two and Three and it is where plan of the development of the world structure comes from.

Man is born in physical body in the certain family, folk, country and during certain time epoch. He does not notice that his whole life is connected with life of the hierarchies of consciousness. His personal life is connected with Angels, which are usually called the Guardian Angels. Life of whole folk depends on Archangels, and influences of Archai are manifested in peculiarity of the rhythm of time in which man is born on the Earth. In the state of consciousness after death man directly perceives the interaction of the hierarchies of consciousness. Instead of movement of the planets of Solar system he experiences the interaction of Spirits of Form, Spirits of Movement and Spirits of Wisdom. Life of the star systems, such as Solar system, appears to him as the manifestation of Spirits of Will, Spirits of Harmony and Spirits of Love. The highest consciousness of Trinity is manifested in life of the whole world structure.

When life of man after death extends up to life of the Trinity, then man has consciousness in causal body. In this state of consciousness man can perceive the free choice which has led to creation of Karma. Now he cannot change his Karma, because it has been created in other state of consciousness on the Earth. However he can make free choice which prepares new conditions for the correction of Karma on the Earth. His free choice leads to the changes in whole Cosmos, which are directed to the creation of such conditions. Man himself interacting with the hierarchies of consciousness prepares conditions for the birth and life in physical body on the Earth in correspondence with his Karma and rhythm of development of consciousness of mankind.

The purpose of incarnation of man in physical body on the Earth is the development of his ‘I’-consciousness. Besides already mentioned seven types of consciousness of man, there are other five stages which will be reached by man in future rhythms of the development of consciousness of mankind. The five others are creative stages of consciousness. They are those of the Creators, of the creative Gods. These twelve stages are related to the twelve signs of the Zodiac.

The stage of consciousness of the creative gods is the stage of consciousness of the heavenly hierarchies, and the higher is the level of consciousness of the hierarchies, the more powerful are beings of the hierarchies. Their power is manifested in the ability to give. Man learns to attain such power when he brings the ability to take in accordance with the ability to give. For this purpose it is necessary for him to pass through the school of life in physical body on the Earth.

The eighth sphere

The septenary rhythm of the development of consciousness of mankind is manifested in every state of consciousness, life and form. This is reflected in seven members of man, which are manifested as relations between the hierarchies of consciousness owing to the free choice of personalities in the states of consciousness Saturn, Sun, Moon and Earth. In each of these states the development of consciousness goes through seven states called the states of life. The state of life is called Round in theosophy. Each state of life passes through seven states of form too. The state of form is called Globe in theosophy. Thus, personalities go through the development of 7*7*7 = 343 states of form. The number 777 seven-seven-seven is called the number of evolution and in this sense the number 444 four-four-four will be the number of present state of the evolution of Earth. Concerning the states of forms this number signifies the middle of the development of the Earth state of consciousness.

All rhythms of consciousness, life and form are manifested together. Therefore personalities which were not able to develop proper their ‘I’-consciousness in the previous states in time, have possibility to continue the development of consciousness in the following states. However as relations between the states of consciousness owing to free choice of personalities change, personalities not always can develop the ‘I’-consciousness by themselves. There could be manifested such relations between the consciousness of personalities and hierarchies that for the stayed behind personality it becomes impossible to develop the ‘I’-consciousness, supported only by its own consciousness. The connection with beings, manifested due to free choice, does not allow the stayed behind personality to direct its own forces to the development of the ‘I’-consciousness.

This is one type of staying behind the development of consciousness of mankind. Personalities want to develop themselves, but cannot because of the connection with beings of the hierarchies of consciousness. Such personalities become the bearers of evil by virtue of their separation from mankind through connection with beings. They can be helped by other personalities, whose consciousness is higher than the level of consciousness of beings with which the stayed behind personalities are connected. The other type of staying behind appears when personalities can change their connection with beings of the hierarchies, but do not want it to do. The stayed behind personalities become not only the bearer of evil, but evil itself. Such state of consciousness that will appear between the stayed behind personalities and beings of the hierarchies, is characterized by the number six-six-six 666. This means personalities can become evil itself when they will pass through the development of 6*6*6 = 216 states of form.

The following Jupiter state of consciousness will be the fifth of seven states. In the 6th state of consciousness, the Venus state of consciousness, in the 6th state of life and in the 6th state of form, when personalities will pass through the development of 216 states of forms, consciousness of the stayed behind personalities will develop such form of separation from mankind, that they become evil itself. This state of separation is called the eighth sphere, or hell, and the number 666 is called the critical number of evolution. In Apocalypse of St. John this number is referred to as the number of animal, or the number of the beast. The number six-six-six designates also Sorat. It is the name of personality which in the Sun state of the development of consciousness was the opponent of Jesus Christ. Sorat will be the leading personality of the eighth sphere. 

Yin and yang

Modern man develops his ‘I’-consciousness in the fourth, the Earth state of consciousness, in the fourth state of life and in the fourth state of form. In each state of form are manifested seven more periods of time. The development of the ‘I’-consciousness of man takes plaxe now in the fifth period which is called Continental. The first period is called Polar, the second – Hyperborean, the third – Lemurian, the fourth – Atlantic. The sixth and seventh periods are specified in the Apocalypse of St. John as the time of opening of seals (6:1-8:1) and of soundings of trumpets (8:2-11:15). 

The periods of the 4-th state of consciousness, 4-th state of life, 4-th state of form are:

1. The Polar period
2. The Hyperborean period
3. The Lemurian period
4. The Atlantean period
5. The Continental period
6. The period of the opening of seals
7. The period of the sounding of trumpets

Each of these seven periods, is subdivided in its turn into seven other sub-periods during which the level of consciousness of mankind changes. Present time corresponds to fifth culture period which is called European. The first culture period is called Pre-Indian, the second – Pre-Persian, the third – Egyptian-Chaldaic--Babylonian, the fourth – Greco-Latin culture period.

The seven culture periods are characterized in the Apocalypse of St. John through letters (messages) to communities (churches) (2:1-3:22). The future sixth culture period is Slavic, and the seventh – American culture period. 

The culture periods of the Continental period are:

1. The Pre-Indian, ancient Indian culture period
2. The Pre-Persian, ancient Persian culture period
3. The Assyrian-Babylonian-Chaldaic-Egyptian-Hebrew culture period
4. The Greco-Latin culture period
5. The European culture period
6. The Slavic culture period
7. The American culture period

In the Atlantean period of the development of the ‘I’-consciousness man has realized the concept of Tao as a rhythm between the Heaven above and the Earth below and as the source of that rhythm. Such rhythm was characterized by two states of consciousness as yin and yang. In any rhythm there are always two alternating states as result of principle of duality. These two states can be considered as two opposites. Because there is nothing unconscious, rhythm can be defined as alternation or change of two states of consciousness. Yin and yang were representations of these two alternating states of consciousness and not the abstract concept of two opposites. 

The consciousness of the hierarchies of consciousness without freedom of choice is always rhythmic, otherwise the hierarchies would have the freedom of choice. That is why man making his free choice through the hierarchies of consciousness without freedom of choice always involves yin and yang in the development of his ‘I’-consciousness.

'''
)

de_evol = _('''                                                                                                                                                                                
Die zehntausend Dinge tragen das Yin und umfangen das Yang. (Tao Te Ching 道德經 42)

'''
)

ru_evol = _('''                                                                                                                                                                                
Десять тысяч вещей несут в себе инь и объемлют ян. (Дао Дэ Цзин 道德經 42)

'''
)

evol = {"en":en_evol, "de":de_evol, "ru":ru_evol, }

st.title(_("Evolution"))

st.write(evol[st.session_state.itaolang])




